### ISSUE TITLE
Create landing page Using Gatsby + Netlify

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#10]
# Gatsby starter: 
- https://gatsby-starter-mate.netlify.com/
- https://www.gatsbyjs.org/starters/EmaSuriano/gatsby-starter-mate/

# Project name:
`COVID Aid`

# Project domain:
`covidaid.app`

# Descriptions / Texts
Here (In Progress): https://docs.google.com/document/d/1pOps_3McLZjdVHJwDutm2kHI1zl4nJ52EbwT6V5yRiE/edit#heading=h.sd2j2tgv9yh7

# Repo
https://github.com/covidaidapp/covidaid

# Checklist
* [x] Look into some Gatsby Starters that look like a good start for us
* [x] Share starters with David, to pass on to implementors
* [x] Delegate work to the taskforce doing the landing page
* [x] Create landing page
* [x] Deploy landing page

**Comment by luisFilipePT** [comment]
@s0 over the weekend hope to have a nice MVP (live) ready to iterate on from Monday forward.

**Comment by s0** [comment]
Perfect thanks! Hoping to have the MVP of the Map by then too!

**Comment by luisFilipePT** [comment]
Map? 🤔 Have to check that

**Comment by luisFilipePT** [comment]
@s0 I guess this can be closed 🤔

**Comment by s0** [comment]
Let's leave it open until it's actually launched on the right domain.

As far as the content goes, it's still connected to contentful right? (I didn't check)
