### ISSUE TITLE
Add styling to requests list (React, HTML, CSS) for Hacktoberfest

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1001]
## Hacktoberfest Introduction

Click [here](#description) for a description of the issue.

We're currently looking for developers who are in React, TypeScript, JavaScript, HTML, CSS, Algolia, and/or Firebase. development.  We strive to implement best practices for implementing Clean Code techniques, including test driven development and object oriented programming.  If you want to learn about these techniques or would like to work on a team that implements these practices, join us!

This is a great team to work if you want to work with other developers or if you want to work solo.  
We have daily pair and mob (collaborative) programming collaborative coding.  In these sessions, you can work on implementing a feature or addressing an issue together with other developers. This is good both for learning about the product when you are first starting and you may find you like working this way better than working on your own.  You will be listed as a co-author for any changes that are committed during a session, which will increase your GitHub contribution statistics.

@ashwinkjoseph or @ethanstrominger  are available to work with you on video conference to fix or implement the hacktoberfest issue or you can fix the issue on your own.

The best way to get ahold of them is through the Reach4Help Slack workspace or email ethanstrominger2@gmail.com.

The readme.md(https://github.com/reach4help/reach4help/blob/hacktoberfest/README.md) will give you information on starting the project.  Please clone and do pull requests from the development branch.

https://github.com/reach4help/reach4help/blob/hacktoberfest/README.md

<a name="description"></a>
## Feature Description

Modify the tabbed page for requests and offers to look like the below image.  We will accept pull requests for implementation of any change that furthers the UI towards this image - you don't need to do all the changes.

The URL path for this page is list/my/offers or list/my/requests.  The URL to create new requests is create/.  The drop down should have the options All Requests, Pending, Ongoing, or Closed.

![image](https://user-images.githubusercontent.com/32078396/95689489-169e0780-0bdf-11eb-8ac6-c41833293ae2.png)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1001)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1001)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1001)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1001)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1001)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1001)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1001)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by edwinfelipe** [comment]
I will try it

**Comment by ethanstrominger** [comment]
@edwinfelipe Great!  If you need help, you can Slack me or @ashwinkjoseph on the Reach4Help channel or mention my name in the issue.  You are more likely to get an answer in Slack.  I am also available for phone / video conference typically 9 AM to 5 PM EST and @ashwinkjoseph is 7.5 hours ahead of me.

**Comment by ethanstrominger** [comment]
Any comments on how to improve the issue or documentation would be greatly appreciated.

**Comment by ethanstrominger** [comment]
@edwinfelipe Please use development branch, instructions previously referred to the hacktoberfest branch.

**Comment by ethanstrominger** [comment]
@edwinfelipe I have not seen any progress, so I am unassigning.

**Comment by ethanstrominger** [comment]
Yes.  @ashwinkjoseph and I are available for questions and we can pair with you.  Slack is the best way to communicate with us on the team-development channel, but we will also reply to posts in this issue.  We like to have updates every couple of days or let us know when you plan to start working on it.  I have assigned it to you.

**Comment by felix-chin** [comment]
@ethanstrominger sounds good. I spent some time on setup and read through the CodingConventions documentation today. I plan to start working on this on Monday.

**Comment by ethanstrominger** [comment]
@felix-chin Can you sign up for Slack and send @ashwinkjoseph a Slack message?  If it works for you, it is easiest for us to communicate there.
