### ISSUE TITLE
Add option to choose language in menu

### ISSUE THREAD

**Issue by ashwinkjoseph** [reach4help/reach4help#1005]
## Hacktoberfest Introduction

Click [here](#description) for a description of the issue.

We're currently looking for developers who are in React, TypeScript, JavaScript, HTML, CSS, Algolia, and/or Firebase. development.  We strive to implement best practices for implementing Clean Code techniques, including test-driven development and object-oriented programming.  If you want to learn about these techniques or would like to work on a team that implements these practices, join us!

This is a great team to work if you want to work with other developers or if you want to work solo and add to your open source contributions on GitHub.
We have daily pair and mob (collaborative) programming collaborative coding sessions.  In these sessions, you can work on implementing a feature or addressing an issue together with other developers. This is good both for learning about the product when you are first starting and you may find you like working this way better than working on your own.  You will be listed as a co-author for any changes that are committed during a session, which will increase your GitHub contribution statistics.

@ashwinkjoseph or @ethanstrominger are available to work with you via video conference to fix or implement the hacktoberfest issue or you can fix the issue on your own.

The best way to get ahold of them is through the Reach4Help [Slack workspace](http://bit.ly/reach4help-slack) or email joseph@reach4help.org or ethanstrominger2@gmail.com.

The [readme.md](https://github.com/reach4help/reach4help/blob/development/README.md) will give you information on starting the project.

<a name="description"></a>
## Feature Description

If you decide to do this issue, please indicate in comment by mentioning @ethanstrominger and @ashwinkjoseph and we will assign you to the issue. If we don't see updates to the bug within 48 hours, we will reopen the issue for others to work on, unless you indicate you plan to start working on it on a certain date.

Expected End Result is to have an option in the side menu that would show the currently active language and provide the user with a dropdown when clicked, listing all the supported languages. It should set the appropriate language in settings once the user selects and use i8n to render the app in the chosen language
![image.png](https://images.zenhubusercontent.com/5e8f583e55bd2e46e02d2e3d/c3ef4953-da22-49c9-a95c-76e043ce805f)

Files and Resources you would need to access to add this feature:(Click on the names of each to be taken to the file or resource)
1. [MenuDrawer](https://github.com/reach4help/reach4help/blob/development/web-client/src/components/MenuDrawer/MenuDrawer.tsx) - The file which renders the menu items.
2. [Previous Implementation](https://github.com/reach4help/reach4help/blob/1399dcba4c72ccb875ea11a77341c167f91cdcb4/web-client/src/modules/login/components/RegistrationSteps/Step1SelectLanguage.tsx#L30) - We had implemented this feature previously in our signup page, the functionality will remain the same, but it'll now be available in the menu drawer instead of the login/signup page. so you can use this file for reference.
3. [i18n configuration](https://github.com/reach4help/reach4help/blob/1399dcba4c72ccb875ea11a77341c167f91cdcb4/web-client/src/translations/i18n.ts#L19) - This is where the i18n tool is configured

Recommended steps - 
1. In menudrawer, add a static drop down to the menu drawer, just above the bottom links which would have display the list of supported languages. (to the previous implementation to see the list of supported languages and how these options were rendered)
2. When the user selects an option, use the method provided by `react-i18n` to change the language to the selected language as done in the previous language.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1005)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ansh-les** [comment]
@ethanstrominger Can I work on this?

**Comment by ansh-saini** [comment]
@ashwinkjoseph Can I work on this?

**Comment by ethanstrominger** [comment]
@ansh-saini Yes.  You can reach out to both @ashwinkjoseph and @ethanstrominger for questions and we can also pair program the solution with you on a video conference.  I have assigned you to the issue.  When do you plan on working on this?  We like to have updates about every 2 days so we know you are making progress, or let us know if you need longer than that.

**Comment by ethanstrominger** [comment]
Joining our Slack workspace s the best way to communicate.

**Comment by ethanstrominger** [comment]
THanks @ansh-saini Closing the issue now.

**Comment by ansh-saini** [comment]
@ethanstrominger @ashwinkjoseph I know you guys are busy but this issue has the `hacktoberfest` label attached to it. Please add the `hacktoberfest-accepted` label to my PR #1017 so it can count towards my contributions.

**Comment by ethanstrominger** [comment]
@ansh-saini Done.  Thanks again for your contribution.
