### ISSUE TITLE
Create test for route that shows map of requests

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1007]
## Hacktoberfest Introduction

Click [here](#description) for a description of the issue.

We're currently looking for developers who are in React, TypeScript, JavaScript, HTML, CSS, Algolia, and/or Firebase. development.  We strive to implement best practices for implementing Clean Code techniques, including test driven development and object oriented programming.  If you want to learn about these techniques or would like to work on a team that implements these practices, join us!

This is a great team to work if you want to work with other developers or if you want to work solo.  
We have daily pair and mob (collaborative) programming collaborative coding.  In these sessions, you can work on implementing a feature or addressing an issue together with other developers. This is good both for learning about the product when you are first starting and you may find you like working this way better than working on your own.  You will be listed as a co-author for any changes that are committed during a session, which will increase your GitHub contribution statistics.

Joseph or Ethan are available to work with you on video conference to fix or implement the hacktoberfest issue or you can fix the issue on your own.

The best way to get ahold of them is through the Reach4Help Slack workspace or email ethanstrominger2@gmail.com.

The [readme.md](https://github.com/reach4help/reach4help/blob/hacktoberfest/README.md) will give you information on starting the project.  While the readme is on the hacktoberfest branch, please do pull requests to the development branch.

<a name="description"></a>
## Feature Description
If you decide to work on this issue, please indicate in comment by mentioning @ethanstrominger and @ashwinkjoseph and we will assign you to the issue. If we don't see updates to the bug within 48 hours, we will reopen the issue for others to work on, unless you indicate you plan to start working on it on a certain date.

Create a test that verifies the route /list/find renders a page with requests displayed.  To see what you should expect, enter http://localhost:8080/list/find.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1007)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ethanstrominger** [comment]
Verify that what you get back includes a map component.  Ask one of us if you need to detail.

**Comment by ethanstrominger** [comment]
Useful links:

https://reactrouter.com/web/guides/testing (edited) 
https://github.com/testing-library/react-testing-library/issues/251#issuecomment-450589074

We can use data-testid prop for finding if a component has rendered or not. (edited)

**Comment by dulcehc** [comment]
Hi @ethanstrominger, I would like to work on this

**Comment by ethanstrominger** [comment]
Okay, I assigned you.  If you have any questions, you can mention @ashwinkjoseph or me  in this issue, but you will get faster results with Slack.  I am on EST, most reliable time to reach me is 9-12 AM EST, 1-4 UTC.  Joseph is on IST.  We can also work together on the issue on video conference - you will still get Hacktoberfest credit!

**Comment by ethanstrominger** [comment]
This is great you are doing this, we really need more testing in the app.

**Comment by ethanstrominger** [comment]
We are now using Slack to discuss this issue.
