### ISSUE TITLE
[Personal-Data] - Add role info screen

### ISSUE THREAD

**Issue by comoser** [reach4help/reach4help#101]
**Personal data screen to allow choosing the user role.**

https://www.figma.com/file/OiU7Tl4k1YFfqZQXxLaRrl/Reach4Help?node-id=597%3A113
![image](https://user-images.githubusercontent.com/52417176/79049587-685bda00-7c1c-11ea-8708-5647c9071a2e.png)

- [x] Build dummy visual page component
- [x] Adapt visuals for mobile view
- [x] Integrate with redux and Firebase

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/101)

*This information is updated automatically. To modify it, please use ZenHub.*

**Blocked By:**

* **[BLOCKING: [#101](https://github.com/reach4help/reach4help/issues/101)]** **[UNASSIGNED]** [#101 - Design View: Role Info](https://github.com/reach4help/reach4help/issues/345)}

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/101)

*This information is updated automatically. To modify it, please use ZenHub.*

**Blocked By:**

* ~~[#101 - Design View: Role Info](https://github.com/reach4help/reach4help/issues/345)~~

**Comment by telmodias** [comment]
1st proposal here https://reach4help.slack.com/archives/C010HTE73A9/p1585611640055000

**Comment by puzzledbytheweb** [comment]
@ashwinkjoseph Is this fully closed? With the Firebase integration and what not?
