### ISSUE TITLE
Translate side menu

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1019]
**Describe the bug**
Menu text is hardcoded and does not translate when you switch languages

**To Reproduce**
Enter URL: localhost:3000/
Change language
Log in
Enter URL: localhost:3000/list/find
Press hamburger menu - it won't be translated
Log out
Press hamburger menu - it won't be translated

**Diagnosis**
Files to change: SideBottomMenu.tsx and SideTopMenu.tsx

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1019)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by leadersheir** [comment]
@ethanstrominger Could you specify the files in which you've made changes for adding translation options?
