### ISSUE TITLE
[SCREEN] CAV intro screen 

### ISSUE THREAD

**Issue by comoser** [reach4help/reach4help#103]
- intro screen for volunteer with the options to:
--- `Your cases`
--- `New cases`

- [ ] Build dummy visual page component
- [ ] Integrate with redux and Firebase

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/103)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by puzzledbytheweb** [comment]
@ashwinkjoseph Is this done?
