### ISSUE TITLE
[PROF.1] As a user, I want to delete my account

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1154]
Action: Next version1.4 As an authenticated user, I want to be able to delete my account.

Acceptance Criteria:
 * All the ongoing requests have to be cancelled.

 * All the ongoing offers have to be cancelled.

 * The request attached to the cancelled offer has to be erased from the database.

 * The closed requests and closed offers that the user was part of are not erased but the user's information is no longer visible and replaced by "Unknown User".

 * All the user's information is erased from the database

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1154)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by shayantist** [comment]
I'd suggest not putting this off for a future version. AFAIK this is already developed (correct me if I'm wrong @ashwinkjosepk) and is important to comply with data privacy laws.

**Comment by ashwinkjoseph** [comment]
> I'd suggest not putting this off for a future version. AFAIK this is already developed (correct me if I'm wrong @ashwinkjosepk) and is important to comply with data privacy laws.

Yes, this is already implemented and is also available in the version that is live right now.
