### ISSUE TITLE
Improve docker-compose file (postgres container)

### ISSUE THREAD

**Issue by wr46** [reach4help/reach4help#116]
Improve [docker-compose.yml](https://github.com/reach4help/reach4help/blob/master/api/docker-compose.yml), so we can have customized data in postgres database configuration.

In addition to database configuration improvements, we must have:
- database name = 'reach4help_api_db'
- database username = 'reach4help_api'
- database username = 'reach4help'

The local [example.env](https://github.com/reach4help/reach4help/blob/master/api/example.env) must be updated, so newcomers could create a local `.env` file.

Note: feel free to improve docker-compose/containers configuration.

**Comment by jonioliveira** [comment]
@wr46 I can handle this

**Comment by jonioliveira** [comment]
can you assign this for me?

**Comment by puzzledbytheweb** [comment]
Sorry, I shouldn't be assigning people regarding the backend team
