### ISSUE TITLE
Dialog for entering phone number UI suggestion

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1170]
h3. UI issues first time creating a request (see attached image)
 * Should say "What country do you live in"?
 * Default to United States?

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1170)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by shayantist** [comment]
Here's how it was designed before: 
![image](https://user-images.githubusercontent.com/29135917/108330498-de937a80-71f7-11eb-992b-fdab5427837a.png)
Probably doesn't require many changes except for leaving the default country as just blank.
