### ISSUE TITLE
Find out if okay to change "Log In" to "Sign In"

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1171]
0

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1171)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by shayantist** [comment]
Fine with me. Seems like there's already some [UX research behind this](https://ux.stackexchange.com/questions/1080/using-sign-in-vs-using-log-in) that supports **"Sign In / Sign Out"** but also **"Register / Join"** instead of **"Sign Up"**
