### ISSUE TITLE
UI for the ' About ' section on the Landing Page

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1176]
UI for the ' About ' section on the Landing Page has to be built as per the figma file provided (attachment About.png provided as well) 

[https://www.figma.com/file/OiU7Tl4k1YFfqZQXxLaRrl/Reach4Help?node-id=6859%3A2]

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1176)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by shayantist** [comment]
Already completed by @leadersheir 's team
