### ISSUE TITLE
UI of the Landing Page top section - Change hard coded colors

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1178]
On the top section of the Landing Page change the hard coded colors with imported colors from JSON

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1178)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by shayantist** [comment]
This was completed already by @Cruebee .
