### ISSUE TITLE
UI: Agree on wording of "Sign Up, Sign Out or Log Out, Sign In or Log In" and implement wording

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1179]
Update menus to be consistent.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1179)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by shayantist** [comment]
Duplicate of #1171
