### ISSUE TITLE
Improve swagger decorators usage for current domain objects

### ISSUE THREAD

**Issue by wr46** [reach4help/reach4help#118]
There are some improvements that we can add into swagger usage in our project:
- Entity attributes validation and documentation
- API responses documentation

Note:
- Check NestJs documentation [here](https://docs.nestjs.com/recipes/swagger)
- We are using the OpenAPI Swagger plugin, so there are some decorators that need to be removed.

**Comment by jonioliveira** [comment]
@wr46 can I do this or is better to leave to another person?

**Comment by wr46** [comment]
Thanks @jonioliveira for you help!
This issue is work in progress in another branch in development.
