### ISSUE TITLE
On Safari, top menu is all crowded together [WARIS]

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1189]
ASSIGNED TO WARIS

![image.png](https://images.zenhubusercontent.com/5f60efde9d012be4aefa063c/8d626b9e-d25d-4035-b923-3fa8a7202b3b)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1189)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by shayantist** [comment]
@leadersheir has this been resolved?

**Comment by leadersheir** [comment]
No, I couldn't take this because of compatibility issues with safari. I'm on linux and I'm a bit too busy to make it work with workarounds. Means I cannot take this on.
