### ISSUE TITLE
Org Map: location should default to user's IP location and should be zoomed in more

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1194]
(CONTINUATION OF #287)
Currently, the map shows you orgs across the world 
![image](https://user-images.githubusercontent.com/29135917/114358726-0f0ee980-9b95-11eb-801e-35e29db36c79.png)

...which is: 

- Not relevant to the orgs in your area you're actually looking for 
- Inefficient because you have to load thousands of markers halfway across the world

To personalize this a bit more without violating privacy, we can use a user's [public IP location](https://www.iplocation.net/) to zoom in on their city/country upon opening the map. 

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1194)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1194)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ssameghini** [comment]
I'll be working on this as well. @satheaki would you like to chat to see what might need to be done?

**Comment by ssameghini** [comment]
I'll show a few screenshots of the browser's geolocation permissions being set, for easier manipulation and testing. This is Chrome, but works as well in Firefox and I presume on other browsers (the feature is supported). Firefox not only asks for permissions, but also for remembering the choice made or ask again on later uses.
I'll be translating from spanish in each case.

![Captura de pantalla de 2021-07-01 21-08-53](https://user-images.githubusercontent.com/9827845/124202903-d9054580-dab1-11eb-985c-40ce18ee154e.png)
> By default, the lock icon next to the navigation bar shows and handles cookies, certificates and permissions. Here, there are no geolocation permissions set.

![Captura de pantalla de 2021-07-01 21-10-28](https://user-images.githubusercontent.com/9827845/124203114-5df05f00-dab2-11eb-8325-ec975033b0b7.png)
> When I click on My Location, the browser prompts for my location. I can Deny or Accept, and the choice gets stored on the browser.

![Captura de pantalla de 2021-07-01 21-12-14](https://user-images.githubusercontent.com/9827845/124203183-8415ff00-dab2-11eb-89c3-201b02b953d1.png)
> Now, if I click again on the lock icon, a Location field has been added, with _Permitir_ -Allow- option set. I can expand the list and change that selection, as it can be seen on the next picture.

![Captura de pantalla de 2021-07-01 21-12-34](https://user-images.githubusercontent.com/9827845/124203306-cdfee500-dab2-11eb-8d93-3d592479d18c.png)
> Here I changed it to _Bloquear_ -Deny or Refuse-, only for illustrating purposes.

![Captura de pantalla de 2021-07-01 21-12-42](https://user-images.githubusercontent.com/9827845/124203445-20d89c80-dab3-11eb-849e-de074623773d.png)
> When I choose _Preguntar (predeterminado)_ -Ask (default)- and close the bar, the browser asks me to reload the page to make the changes. And on next visit, the permission is deleted and pending to prompt.
