### ISSUE TITLE
Get Guidance for GDPR

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#12]
* [x] Find someone that knows about GDPR (Europe and California)
* [x] Add them to the project or ask for some guidelines
* [x] Create user data security policy document
* [ ] Document Information security technical requirements

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/12)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by TheRealAlexV** [comment]
Create user data security policy document:
https://docs.google.com/document/d/1EPT8iP0ChsQLirKgiJUS2DS7zWB3FUjbnbarnFPB2p8

Paging @sabind @mdeous and @s0 for review
