### ISSUE TITLE
Prevent adding duplicate markers from Mutual Aid Hub

### ISSUE THREAD

**Issue by shayantist** [reach4help/reach4help#1201]
The map is once again being populated with duplicate data: 
![image](https://user-images.githubusercontent.com/29135917/111415511-457b5500-870c-11eb-83e3-ac8204b27756.png)

The issue seems to be in how we fetch data from Mutual Aid Hub: 
![image](https://user-images.githubusercontent.com/29135917/111415547-575cf800-870c-11eb-9f89-542d8fb2fd2b.png)

....which means we need to debug [`functions/src/pubsub/schedule/sync-mutualaidhub.ts`](https://github.com/reach4help/reach4help/tree/development/functions/src/pubsub/schedule/sync-mutualaidhub.ts)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1201)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1201)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ethanstrominger** [comment]
@hajarNasr - Please do fix on branch from staging.  Shayan has details on the code.  See code under <root>/functions.  "yarn" to install code and "yarn serve" to start up.
