### ISSUE TITLE
Add createdAt, updatedAt and verifiedAt to map marker

### ISSUE THREAD

**Issue by shayantist** [reach4help/reach4help#1203]
For more info check our [updated data dictionary](https://docs.google.com/spreadsheets/d/1s9zyIepdXjMIdP4jRl7I33fADTw8VppwUDEL22K3uFw/edit#gid=0).

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1203)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by jensren** [comment]
For the directories map and model:
1. Objects with objectID should also have createdAt, updatedAt and verifiedAt
2. Upon creating object with objectID, at createdAt with current Date
3. Don't change dataDriver.ts or JSON files
