### ISSUE TITLE
Marker not appearing for a long period of time on map when you add a new organization

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1205]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1205)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by shayantist** [comment]
This cloud function is what generates .json files from our map markers and uploads them to our storage bucket. The only issue now is that it's only run every 2 hours, which isn't soon enough to see immediate changes. 
![image](https://user-images.githubusercontent.com/29135917/108893036-ce85fb80-763a-11eb-8b41-e066a0f55a82.png)

@s0 left a todo about reducing this delay regarding selectively reading and updating only changed documents, but I'm not too sure how to go about doing that without parsing through the whole JSON onWrite to a marker. 
![image](https://user-images.githubusercontent.com/29135917/108893143-f1181480-763a-11eb-991d-bfae5f038138.png)

Could a potential temporary solution for now just be to generate the data files from scratch onWrite? 

A rationale for this is that we'll likely not have too many organizations added to map every day anyway (~100 max/day) so the number of reads we'll make to Firestore shouldn't be much higher (in fact, they'd be lower on days where <12 organizations are added).

**Comment by ethanstrominger** [comment]
When Shayan and I looked at the log, it looked like the cloud function was run close to when the data was entered.

**Comment by ethanstrominger** [comment]
Diagnosis: Looks like cloud function is running.  It is just not adding new data to the json file.  Next step may be to add log statements to see what is happening.

**Comment by shayantist** [comment]
Update: I've set up generateDataFiles to work onWrite to the markers collection in the staging environment. Seems to work well with a 12 second lag whenever we create or update any markers on the map. 

Will work out any potential issues w/ @ethanstrominger tonight before pushing out to production.
