### ISSUE TITLE
UI feedback needed: Viewing and accepting requests/offers

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1213]
On my requests, can we have a link that says "3 offers" or a button that says "View 3 Offers"?
On map page, can we change "Accept Help" to "Ask for Help"?

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1213)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by shayantist** [comment]
> On my requests, can we have a link that says "3 offers" or a button that says "View 3 Offers"?

Good idea. Try this: 
![image](https://user-images.githubusercontent.com/29135917/114355551-6b700a00-9b91-11eb-9987-85aad3c31370.png)


> On map page, can we change "Accept Help" to "Ask for Help"?

Yeah, that works better. We'll update the Figma accordingly.
