### ISSUE TITLE
Set up heroku deployment pipeline from dev to prod

### ISSUE THREAD

**Issue by edmkitty** [reach4help/reach4help#125]
Dependent on #126 

In order to do this:
- [x] Create Staging App
- [x] Add PG Add-on to Staging
- [x] Create Production App
- [x] Add PG Add-on to Production
- [x] Update `Procfile` to run migration on `release` according to [here](https://devcenter.heroku.com/articles/release-phase)

**Comment by sabind** [comment]
Now that we have an env all we need to do is create a staging and prod app with a PG addon. 

I'll have to updated the `Procfile` to run a `Release` step so that as we promote up the chain the migrations will continue to run.
