### ISSUE TITLE
Analyze the best approach to authenticate a user in the platform

### ISSUE THREAD

**Issue by wr46** [reach4help/reach4help#127]
We need to implement the best approach to authenticate a user taking into account our application flow.

Requirements:
- User must be prompted by facebook authentication. (Frontend)
- The Frontend will use our API to fetch/store data by User
- API data must be protected regardless of the API client

Notes:
- Frontend workflow suggestion [here](https://www.lucidchart.com/documents/edit/1a6804c8-a89e-4d88-be32-871d8478f015/0_0?shared=true)
- Suggestion for a third party security manager [here](https://auth0.com/)
- Facebook security guidelines [here](https://developers.facebook.com/docs/facebook-login/security/)

**Comment by jpmarques66** [comment]
@wr46 Does this issue still make sense with firebase migration?
