### ISSUE TITLE
Add ability to query markers based on services

### ISSUE THREAD

**Issue by shayantist** [reach4help/reach4help#1271]
Right now, we're only able to query our map at a high level based on the type of organization: 
![image](https://user-images.githubusercontent.com/29135917/118362444-5da70d80-b5b1-11eb-9ad0-4d302c2cfcdc.png)

However, people currently have no way to find looking for organizations providing specific services (i.e. food, information, oxygen cylinders, vaccinations). We need to add another dropdown to query by services. 
![image](https://user-images.githubusercontent.com/29135917/118362480-76afbe80-b5b1-11eb-8abb-87d5906ddb4b.png)

UI should look something like this (specifically the black circle): 
![image](https://user-images.githubusercontent.com/29135917/121533827-783e9c00-ca22-11eb-9a0c-44aebe5ef842.png)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1271)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ethanstrominger** [comment]
See issue #1335 for front end.

**Comment by ssameghini** [comment]
I'd like to help @jensren with this. I assume we are working on the 'map' branch, right?
