### ISSUE TITLE
Setup of Twilio service

### ISSUE THREAD

**Issue by telmodias** [reach4help/reach4help#129]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/129)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by s0** [comment]
The status of this has changed right @telmodias ?

**Comment by telmodias** [comment]
Yes , for some reason I have difficulties to manage my issues on the project. I was checking yesterday and only had 3, but this was not present. I'll mark it done.
