### ISSUE TITLE
Contacting Nextdoor

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#13]
> @schowdhury8
> (submitted a contact form and contacted the CEO thru LinkedIn)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/13)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Never heard back... Ah well.
