### ISSUE TITLE
Deduplicate rows using Airtable's dedupe app

### ISSUE THREAD

**Issue by shayantist** [reach4help/reach4help#1334]
Assigned to: **Justin Lam** (but more people are needed!) 
The data by the teams in the field has its fair share of errors (as is expected by a large volume of manually collected data). Fortunately, Airtable has a brilliant built-in utility to help us deduplicate rows using a subset of identical fields: 
![image](https://user-images.githubusercontent.com/29135917/120681423-2eebcb00-c4bd-11eb-8247-69b26528b4fb.png)

A good place to start is to see rows with the **same phone number and location (state, city)** but different fields for everything else. There's a good bet that they're actually dupes given the same phone number. 
![image](https://user-images.githubusercontent.com/29135917/121457891-3d107e80-c9ca-11eb-9190-b00e1a8acf79.png)

For example, here we see 5 records with the same number (4 and 5 are cut off unfo): 
![image](https://user-images.githubusercontent.com/29135917/121458308-f0797300-c9ca-11eb-8c5a-200f01e3e245.png)

I was planning on writing up a step-by-step process but realized it'll be a lot faster and intuitive if I just give a quick demo over a call, so hmu if you're interested in working on this.

**Comment by ethanstrominger** [comment]
@schowdhury8 What do you want to de-duplicate?

**Comment by shayantist** [comment]
> @schowdhury8 What do you want to de-duplicate?

Updated the description

**Comment by ethanstrominger** [comment]
@schowdhury8 Which Airtable table?  To confirm, no programming, this is a one time effort?

**Comment by shayantist** [comment]
@tzou2024 completed the bulk of this, so we're good to go now!
