### ISSUE TITLE
Allow user to select services for all types under "Add Information"

### ISSUE THREAD

**Issue by shayantist** [reach4help/reach4help#1335]
Currently, we're not able to select services provided by any other type of entity on our map except organization: 
![image](https://user-images.githubusercontent.com/29135917/120764902-75333f80-c53a-11eb-9aaa-32abc1b71e48.png)

Expected behavior: 
![image](https://user-images.githubusercontent.com/29135917/120765060-a27fed80-c53a-11eb-855b-f7201570f089.png)

**Comment by ssameghini** [comment]
Hi, I'd like to help with this one!

**Comment by ethanstrominger** [comment]
@schowdhury8 Proposal for the UI: add button "Advanced Query" to the default search dialog.  When clicked, opens a dialog box where user can select one or more services.  

Add Search button to both the default search and the advanced search.

**Comment by ethanstrominger** [comment]
See issue #1271 for backend.

**Comment by ssameghini** [comment]
Will do! Thank you for the clarification, the previous description had screenshots of the "Add information" view, not the actual Search box and dialog.

**Comment by shayantist** [comment]
> @schowdhury8 Proposal for the UI: add button "Advanced Query" to the default search dialog. When clicked, opens a dialog box where user can select one or more services.
> 
> Add Search button to both the default search and the advanced search.

Probably not needed, since it overcomplicates things. There's no additional UI requirements here. All we need is just to replicate the same thing we see for "Organization" for "Other" (and any other selection)
