### ISSUE TITLE
Figure out Algolia analytics - can it capture what queries are made?

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1351]

**Comment by disdyakis** [comment]
The default behavior of Algolia is that it will give use analytics for the following, with no configuration needed on our end:

> - Overall search counts
> - A “No search result” rate
> - Top searches
> - Top searches with no results
> - Top results
> - If a filter is provided, top searches associated with that filter
> - Top filter attributes and filter values
> - Distinct count of IP addresses / Users
> - Top countries

[Further reading](https://www.algolia.com/doc/guides/getting-insights-and-analytics/search-analytics/out-of-the-box-analytics/)
