### ISSUE TITLE
Add multi-select for marker types

### ISSUE THREAD

**Issue by shayantist** [reach4help/reach4help#1371]
Right now, we only have the option to select all the marker types (denoted by "Any") or just one. Adding a multi-select to allow users to find only "Hospitals" and "Medical Services" while filtering has been asked for by some users. 
![image](https://user-images.githubusercontent.com/29135917/121806243-e9738e80-cc70-11eb-954c-f6c0d7fe9be6.png)

Instead of implementing this from scratch, using a library like [react-select](https://react-select.com/home) would be a good starting point to save time.

After implementing this, we should do the same for our various service types as well.

**Comment by ssameghini** [comment]
I'll take it!
