### ISSUE TITLE
Map filter bug: selecting too many options in multi-select filter makes panel too long

### ISSUE THREAD

**Issue by jensren** [reach4help/reach4help#1421]
**Describe the bug**
Selecting more options in the multi-select filter makes the panel get longer. As a result, if too many options are selected the panel can become too long to fit on the screen.
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/41408654/125362979-c99dbc00-e33d-11eb-8464-8f4676eeccf7.png">

Also, if the panel is too long the hideable results list will not work properly. If the panel still has some room left on the page, the results list will look very small:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/41408654/125363139-15e8fc00-e33e-11eb-8659-74e217c7b6e6.png">
Adding even more options to the multi-select drop-downs makes the results not able to pop out at all:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/41408654/125363223-3c0e9c00-e33e-11eb-82fc-7b9e12c737e7.png">

**To Reproduce**
1. Go to the multi-select drop-downs (organization type and services offered) and keep selecting more options

**Expected behavior**
The panel should have a size limit, and if the user keeps selecting more options the panel should start scrolling. If the user opens a drop-down menu, the list of drop-down options should still be able to scroll  independently of the whole panel, as seen in the screenshot:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/41408654/125363508-ba6b3e00-e33e-11eb-9a27-7236f6a44c65.png">

**Comment by shayantist** [comment]
Perhaps instead of listing out all the options, we can have something like this:
https://medium.com/@compmonk/react-multi-select-with-check-boxes-and-select-all-option-bd16941538f3 
![image](https://user-images.githubusercontent.com/29135917/129620595-7d428437-40ff-4a96-b05a-66ba9d7d8e7a.png)

**Comment by jensren** [comment]
@schowdhury8 Discussed with Ethan today and we decided to go with the checkbox multiselect. I'll implement it when I get a chance :)
