### ISSUE TITLE
Write up a constitution of Reach4Help

### ISSUE THREAD

**Issue by puzzledbytheweb** [reach4help/reach4help#153]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/153)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Drafted up a [constitution/mission statement](https://docs.google.com/document/d/150ELY9bRB7Vcn4VD9dEVw3Tvzg1cu_SVaaV1jesvxKk/edit). The outreach team approved of it, so it's being shared with our new PR firm Cognito!
