### ISSUE TITLE
Email NPO guy and cc Sam & Pedro

### ISSUE THREAD

**Issue by schowdhury8** [reach4help/reach4help#157]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/157)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by puzzledbytheweb** [comment]
@schowdhury8 Do we have news on this or should we close?
