### ISSUE TITLE
Implement View: Volunteer offers (Accept / Reject Request)

### ISSUE THREAD

**Issue by comoser** [reach4help/reach4help#161]
(UPDATED 19-05-2020)
**Viewing CAV offers:**
The PIN (Person in Need) can view the CAVs' (Volunteers) offers and accept or reject them to enable the CAV to access PIN's information and proceed to fulfill the request

**User Journey on this screen:**
The PIN can view his request and it's details in the top with an "Open" status
The offer / offers from CAV's are displayed below
Each CAV offer, has some details about him: number of hearts, rating, distance
The PIN can accept or decline the CAV's offer
The PIN can only accept one offer from a CAV

**Screen details:**
As displayed in Figma / capture below, the screen is composed by:
-The request's details
-The CAV's offers on the PIN's request
![image](https://user-images.githubusercontent.com/1456473/82284988-dd43d180-9989-11ea-98ee-52aa12ad3db4.png)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/161)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#334 - View: PIN: Accept / Reject Request](https://github.com/reach4help/reach4help/issues/334)

**Blocked By:**

* ~~[#161 - Design Mobile View: Accept / Reject Request](https://github.com/reach4help/reach4help/issues/355)~~

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/161)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#334 - View: PIN: Accept / Reject Request](https://github.com/reach4help/reach4help/issues/334)

**Blocked By:**

* ~~[#161 - Design Mobile View: Accept / Reject Request](https://github.com/reach4help/reach4help/issues/355)~~

**Comment by fulin426** [comment]
This is assigned to me as of May 18th
