### ISSUE TITLE
[New Request] - Add new request screen

### ISSUE THREAD

**Issue by comoser** [reach4help/reach4help#162]
(UPDATED 19-05-2020)
**Creating a request:**
The PIN (Person in Need) can create his request with its details so that the CAV (Volunteer) that fulfills the request has all the details he needs.

**User Journey on this screen:**
To create a request, the PIN enters (all these inputs are mandatory):
 -his address either by text entry or by putting a location pointer
 -the type of request
 -the details of his request

If the PIN wants to proceed he presses "Next", if the PIN wants to cancel he presses "Cancel"

 A-Pressing "Cancel":
  The user is redirect to "How can we assist you?" screen

 B-Pressing "Next":
  The map points to the location where the request has to be brought to by the CAV
  The input data is frozen for checking. The PIN checks the information he is about to send.
  If the PIN wants to Submit his request he presses "Submit the request", if the PIN wants to go back 
  to modify his input, he presses "back": 

- Pressing "Back": The user is redirected to the previous screen to correct his data
- Pressing "Submit Request": The request is sent to Back-end, and a confirmation screen is displayed.

**Screen details:** 
As displayed in Figma / capture below, the screen is composed by:
-A top panel displaying The number of volunteers around
-Map
-Request panel
![image](https://user-images.githubusercontent.com/1456473/82277009-59341e80-9976-11ea-99d0-0a2f5cc16a24.png)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/162)

*This information is updated automatically. To modify it, please use ZenHub.*

**Blocked By:**

* **[BLOCKING: [#102](https://github.com/reach4help/reach4help/issues/102), [#160](https://github.com/reach4help/reach4help/issues/160), [#162](https://github.com/reach4help/reach4help/issues/162), [#348](https://github.com/reach4help/reach4help/issues/348)]** **[UNASSIGNED]** [#162 - implement component: layout / header + side drawer](https://github.com/reach4help/reach4help/issues/324)}
* **[BLOCKING: [#162](https://github.com/reach4help/reach4help/issues/162)]** **[UNASSIGNED]** [#162 - Design view: PIN: Request something new](https://github.com/reach4help/reach4help/issues/346)}

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/162)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#330 - View: PIN: Request something new](https://github.com/reach4help/reach4help/issues/330)

**Blocked By:**

* ~~[#162 - implement component: layout / header + side drawer](https://github.com/reach4help/reach4help/issues/324)~~
* ~~[#162 - Design view: PIN: Request something new](https://github.com/reach4help/reach4help/issues/346)~~

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/162)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#330 - View: PIN: Request something new](https://github.com/reach4help/reach4help/issues/330)

**Blocked By:**

* ~~[#162 - implement component: layout / header + side drawer](https://github.com/reach4help/reach4help/issues/324)~~
* ~~[#162 - Design view: PIN: Request something new](https://github.com/reach4help/reach4help/issues/346)~~

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/162)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#330 - View: PIN: Request something new](https://github.com/reach4help/reach4help/issues/330)

**Blocked By:**

* ~~[#162 - implement component: layout / header + side drawer](https://github.com/reach4help/reach4help/issues/324)~~
* ~~[#162 - Design view: PIN: Request something new](https://github.com/reach4help/reach4help/issues/346)~~

**Comment by mcverter** [comment]
Notes from Joseph's explanation:

DashboardLayout 

(BottomNavbar New RequestButton  OpenRequestModal)  Change that to a function that  requests/open

new module should be named as newRequest or requests

title details 
request address needs to be added to
for this we can use the navigator to get the GPS location.  
if user does not give you their location
allow the user to edit the address
when you are submitting.  you need to encode that into longitude and latitude


SetRequest action creator to change the request.   
latLng.  we don't set that to the 
address tp the Request model
LatLng and address in workds

make modification in the model
you need to make it in the interface first and then in the class 

you have to make this change in the modal thing

then you popup and you show the user

Only show the user location
don't show anything around it

**Comment by mcverter** [comment]
Interface Changes:
---------------------------
* Remove current modal interface for making request
* Create a new route, /requests/new that shows the flow given above

Model changes
---------------------
Request Model and Interface require new property for "streetAddress" 

New UI Components
----------------------------
Request Entry
Request Review
Request Confirm

Map
------
Address input on form must be coordinated with map.
Request can be issued from current location or by specifying address on input form.

**Comment by isma-osy** [comment]
Moved to Icebox to be able to use zenhub as our clean unique project management tool
