### ISSUE TITLE
Can't start web-client on Windows

### ISSUE THREAD

**Issue by puzzledbytheweb** [reach4help/reach4help#166]
```
-> yarn start

yarn run v1.22.4
$ SKIP_PREFLIGHT_CHECK=true react-scripts start
'SKIP_PREFLIGHT_CHECK' is not recognized as an internal or external command,
operable program or batch file.
```

I'll install cross-env as a dev dependency to enable this

**Comment by sabind** [comment]
ouch, not a windows user 😞

**Comment by sabind** [comment]
However we won't likely accept that PR. Please use `bash` on windows.

**Comment by puzzledbytheweb** [comment]
Hmm. Could this be a detractor for newcomers?

**Comment by sabind** [comment]
I won't speak for the whole team, but that's an awkward dependency to toss in that will touch all of our build scripts, ci/cd, pipelines etc, and some commands run after dev pruning. The impact is not minor.

**Comment by puzzledbytheweb** [comment]
I agree with you. I'll install and close the issue if there are no issues with that

**Comment by puzzledbytheweb** [comment]
So, I'm still not able to run the app without the cross-env package. I will try again tomorrow.
In Windows, to set a Global Variable in a command I need to run `set SKIP_PREFLIGHT_CHECK=true`, as opposed to just `SKIP_PREFLIGHT_CHECK=true`. What cross-env does is to abstract us from doing this.

If someone has experience with this I would very much thank you for your help. This is frustrating :/

**Comment by sabind** [comment]
I agree that `cross-env` would help in this manner, but am worried about adding it. I'd leave this question with the other leads (@s0, @wr46 @comoser). They should be able to help out with some advice. I've never had this problem (always ran Linux for dev on Windows)

**Comment by comoser** [comment]
Opened #168 to see if this solves it. Assuming everyone has docker engine installed. And I know the docker engine works differently on windows, so it may need some kind of adaptations

**Comment by puzzledbytheweb** [comment]
Thank you @comoser. Nonetheless, I was a bit too tired yesterday to follow through the whole installation of the Linux subsystem on Windows. I'm trying out this morning and will give you guys some feedback

**Comment by puzzledbytheweb** [comment]
I have installed successfully Ubuntu in Windows and I'm able to run this now. I will close this issue.

Thanks guys!
