### ISSUE TITLE
Virtualize frontend env with docker

### ISSUE THREAD

**Issue by comoser** [reach4help/reach4help#168]
Virtualize the env with docker, to see if we can fix local running problems.
- map node_modules to our local node_modules, no need to install them in the `Dockerfile`
- map root project folder to support HMR

Make these mapping with `docker-compose`, since the backend is using it too, and later on we can do a `docker-compose up` that lifts the DB, the backend and the frontend in one go

References #166

**Comment by puzzledbytheweb** [comment]
I think that for the time being this might be cumbersome and create unnecessary complexity. I solve the #166 so apparently there is no urgency in this.

I'll leave it to you to close this issue if want.
