### ISSUE TITLE
Contact and coordinate with people behind https://github.com/tgalopin/enpremiereligne.fr

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#19]
Would be good to find out what the long-term project goals are, what the pain-points they've experienced are etc...

See: https://helpfulengineering.slack.com/archives/C010313P4A3/p1584745422326100

**Comment by puzzledbytheweb** [comment]
I'll contact them right away! Will come back with info!

**Comment by puzzledbytheweb** [comment]
Contacted. Waiting for response

**Comment by etiennepilon** [comment]
I've contacted them a few days ago. They are launching an international version of their app. That's all the information I've got from them for now.

**Comment by etiennepilon** [comment]
They are having a call to share their experience tomorrow at 9pm EST, will update the group after  that time. Anyone is welcome to join.

**Comment by puzzledbytheweb** [comment]
@etiennepilon Thank you so much for contacting them! You can post that feedback in this issue ;)

**Comment by etiennepilon** [comment]
I’ve talked with the guys from enpremiereligne.fr today and they mentioned most of the work is in the promotion/marketing/operations/partnerships. They put in 12h/day x3 people + a few people that are part time.
The weakest link is of non-technical nature. So if those aren’t tackled, there are little points in developing the platform itself.
Also, one of the key point they mentioned is to keep the scope as narrow as possible given there are tons of platforms being developed in parallel. Exemple: Many platforms were developed to provide housing closer to the hospitals to the health care professionals. AirBnB launch the same thing, all those platform died.

**Comment by puzzledbytheweb** [comment]
@etiennepilon Thank you for talking with them. Definitely the partnership part is something we need to be better at.

I'll close this issue.
