### ISSUE TITLE
Register a Google for Nonprofits account

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#20]
https://www.google.com/nonprofits/

This will allow us to use G Suite for free, and get more maps api credits (which may be necessary for the maps project).

It's likely that we won't be able to get this unless we're a registered non-profit in some country, which I imagine takes a while. Though a post on slack indicates that it may be immediate: https://helpfulengineering.slack.com/archives/CUVPGT54J/p1584332529096600

In any case, I've reached out to [@googlenonprofit](https://twitter.com/googlenonprofit) on twitter over DM to see if they have any flexibility on this, will update here...

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/20)

*This information is updated automatically. To modify it, please use ZenHub.*

**Blocked By:**

* **[BLOCKING: [#392](https://github.com/reach4help/reach4help/issues/392), [#394](https://github.com/reach4help/reach4help/issues/394), [#20](https://github.com/reach4help/reach4help/issues/20), [#397](https://github.com/reach4help/reach4help/issues/397)]** [[@schowdhury8](https://github.com/schowdhury8), [@puzzledbytheweb](https://github.com/puzzledbytheweb)] [#20 - Register as NGO / NPO](https://github.com/reach4help/reach4help/issues/21)

**Comment by shayantist** [comment]
This is actually done, so it can stay closed!
