### ISSUE TITLE
Update UX to allow for regional roll-out

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#215]
We won't be able to release the app globally from the start, and will need a slow roll-out to individual regions.

Let's add a UX view to support this (probably after someone enters their address ?)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/215)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by telmodias** [comment]
@all-contributors please add @telmodias for ideas, doc, code, review, projectManagement, design
