### ISSUE TITLE
Get onboarded to mutual-aid slack

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#216]
Details: https://docs.google.com/document/d/1kEipd8DZGZSCVeE242o24D5ohOOaj1pv3eqJWW1kB8w/edit

This slack can provide a valuable network to connect to groups and organizations that could benefit from and use our software.

* @s0 

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/216)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by s0** [comment]
Initial form filled out here: https://docs.google.com/forms/d/e/1FAIpQLSec5f4MHWMJ68wKfrRW7qhAvmo1F7vcbnSBIbZhAezaGAL8kQ/viewform

**Comment by puzzledbytheweb** [comment]
I have also filled the form while having no knowledge of this issue. Waiting for an invitation

**Comment by puzzledbytheweb** [comment]
We're in!
