### ISSUE TITLE
Split up skills Google Sheet provide a clear distinction of teams, so people can join more effectively

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#22]
* [x] Break current team spreadsheet down to teams
* [x] Define suggested skills for front end, backend and infra teams.
* [x] Post in channel for people to start to put them selves in to the teams they want to join.

**Comment by puzzledbytheweb** [comment]
I've splitted up the document. Wating for team leads to write the skills they need so we can close the task

**Comment by puzzledbytheweb** [comment]
@schowdhury8 Is going to create a Google Form to ease the onboarding process
