### ISSUE TITLE
Investigate redux-first-router

### ISSUE THREAD

**Issue by jpmarques66** [reach4help/reach4help#220]
This might come in handy, especially if we need to handle URL properties. 

What would be the cost of adding this later? Is it worth adding it right now?
https://github.com/faceyspacey/redux-first-router

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/220)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by puzzledbytheweb** [comment]
@ashwinkjoseph Is this something that is already implemented in our app/something we want to move forward?
