### ISSUE TITLE
Assess how to collect insights from the field to generate / monitor KPIs.

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#24]
Related: #23 

In order to improve the service to deliver, we will constantly need to collect feedbacks from users. This means:
- Asking feedback
- Collecting / stocking insights
- Reporting / monitoring KPIs

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/24)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by puzzledbytheweb** [comment]
- I think that the rating system will provide good feedback and can act as a KPI.
- We can also ask periodically for feedback for both sides of the service (Volunteers and PINs)
- The feedback regarding the organizations will be collected now that we have a name/domain and I'll update this issue
