### ISSUE TITLE
Site - Create a section for supporters / sponsors

### ISSUE THREAD

**Issue by telmodias** [reach4help/reach4help#246]
We should create a section on the website that could allow us to show sponsors / supporters where we could display logos of companies and individuals that support the project, i.e. Twilio and others, also possibly define levels of sponsorship like Gold, Silver, Bronze and individuals I would not make a distinction. For company sponsors the several levels could correspond to a certain amount of money or value of services, either by monthly or globally.

**Comment by s0** [comment]
We should still add a link to the opencollective though
