### ISSUE TITLE
[SCREEN] Landing page with geolocation

### ISSUE THREAD

**Issue by telmodias** [reach4help/reach4help#255]
Create the landing page, showing text describing the need for geolocation to verify if our product is available in the user's area, and a button that requests access to the user geolocation and triggers the filtering actions to either allow the user to 

- [x] Build visual page component
- [x] integrate with geolocation
- [ ] integrate with redux

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/255)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by telmodias** [comment]
@jpmarques66 cannot yet fully understand redux implementation. trying to pass user coordinates between components via redux, unsuccessfully. Can you take look and correct what I did wrong to see if I can understand how this implementation works ?

**Comment by telmodias** [comment]
This issue has already some development on it but will be removed once the implementation of #383 is completed, because #383 replaces this functionality since the geolocation request has moved from the "Landing Page" to the "User Info" screen (aka "Personal-Data", aka "Name & Address").

**Comment by ashwinkjoseph** [comment]
@telmodias I have integrated redux for the personal data page.
Is this the same as that? because it doesn't have any feature of filtering users based on location.
where are we storing data for that? is that supposed to be dynamic based on available volunteer locations?
