### ISSUE TITLE
Add Slack to list of Thank You's on site

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#261]
On here https://reach4help.org/, we should link to https://slack.com/intl/en-gb/resources/using-slack/covid-help now that we're upgraded to standard.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/261)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by puzzledbytheweb** [comment]
This is great! Thanks ;)
