### ISSUE TITLE
Landing page overhaul

### ISSUE THREAD

**Issue by schowdhury8** [reach4help/reach4help#269]
Currently, I'd say our [landing page](https://reach4help.org/) is a tad bit lackluster with regards to expressing who we are. As we're broadening our reach to general audiences such as PINs, volunteers, partners, potential donors and non-technical contributors, we need to have a professional-looking central website that conveys our mission, our team, our partners, our achievements, etc. to let the world gain a holistic view of our project. 

Before the actual frontend development, the beginning stages are gonna be more in line with graphic design and UX flow before the actual frontend dev bit. Ideally, we want a few iterations that the UX and User Testing teams can provide more detailed feedback on. 

Starting with design, Miranda's already made some amazing stuff through our [brief](https://drive.google.com/file/d/1O7QpZF6iJyCa8GGzFVazP_-5ldiGCVwU/view?usp=sharing) and [marketing materials](https://drive.google.com/drive/u/0/folders/12uvpy_LPrF0MJlzzBKNAi2h_Qm9tDXvy) which are a fantastic start. I've identified a few landing pages that work as good models such as [VolunteerMatch](https://www.volunteermatch.org/) and [Webflow](https://webflow.com/). I also found a few cool looking templates [here](https://cruip.com/) that could be useful for designing. 

**Suggestion** : 

Please consider creating a new section on the website, specifically to promote our sponsors and supporters .  As a suggestion please check this [screen mock](https://drive.google.com/file/d/1N8UxNCKkeB1_KW5ZZXQ-GoI95Rh1YxA_/view?usp=sharing) where the sponsors logos could be shown in our homepage; now that we start to have more and more sponsors… such as Slack and Figma … I think this could improve our chances of getting more support and our sponsors would be much more motivated .

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/269)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by puzzledbytheweb** [comment]
Webflow looks good, as do some of the templates. The Volunteer Match though, I don't like it. 
We should open up a poll in the slack channel about this

**Comment by schowdhury8** [comment]
Although I do agree that the visual design of VolunteerMatch is a bit dated, it does seem like a very inviting and nice social environment that you'd want to support. Also before we present options to the whole team, we should probably come up with some options of our own as well after marketing design discuss this a bit.
