### ISSUE TITLE
When the status of a request is updated a `timeline_item` record should be created.

### ISSUE THREAD

**Issue by sabind** [reach4help/reach4help#279]
The timeline item record should include a snapshot of the request as well as a snapshot of the offer if the status is > `pending`

if the request status changes back to pending we have to clear out the associated `cavUserRef` as they are no longer the active CAV for the request.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/279)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [[@sabind](https://github.com/sabind)] [#359 - Complete backend for MVP](https://github.com/reach4help/reach4help/issues/359)

**Comment by puzzledbytheweb** [comment]
@sabind is this finished? I believe so but wanted to ask. Reopen if I'm mistaken
