### ISSUE TITLE
Center map on startup!

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#287]
Right now, the default coordinates (0, 0) are not very useful for many resolutions, and most of the markers start off the end of the map.

We should start the map at the center of the markers we know about instead, something like:

* lat: `(max(lat) + min(lat)) / 2)`
* lng: `(max(lng) + min(lng)) / 2)`

Relevant lines here: https://github.com/reach4help/reach4help/blob/master/map/src/components/map-utils/google-maps.ts#L7

**Comment by btuerker** [comment]
Hi @s0,

I think we'd better use the average. 

Here are the results for both on a smaller screen and a wider screen:
### Case 1:
- lat: (max(lat) + min(lat)) / 2)
- lng: (max(lng) + min(lng)) / 2)

![Screen Shot 2020-04-07 at 5 23 00 PM](https://user-images.githubusercontent.com/46192266/78680809-a2636e00-78f4-11ea-95db-150367c10855.png)
![Screen Shot 2020-04-07 at 5 23 09 PM](https://user-images.githubusercontent.com/46192266/78680832-a7c0b880-78f4-11ea-839d-b66a6cfbefee.png)

### Case 2:
lat: average(lat)
lng: average(lng)
![Screen Shot 2020-04-07 at 5 18 17 PM](https://user-images.githubusercontent.com/46192266/78680980-d8085700-78f4-11ea-9ec7-f093775a2fa2.png)
![Screen Shot 2020-04-07 at 5 18 26 PM](https://user-images.githubusercontent.com/46192266/78680990-d9398400-78f4-11ea-9a2f-037be9b40141.png)

**Comment by s0** [comment]
@btuerker hmm okay that makes sense, thanks for the screenshots. Please feel free to do averages instead and open a PR :)
