### ISSUE TITLE
Add google analytics to map with cookie consent

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#291]
Related to #290

We should add something (not too disruptive) to the UI that asks users if they're okay with us dropping cookies for google analytics, and if so, at that point enable google analytics for the map.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/291)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [[@isma-osy](https://github.com/isma-osy)] [#413 - Prepare MAP for Go-To-Market / Marketing strategy](https://github.com/reach4help/reach4help/issues/413)

**Comment by mdeous** [comment]
Once we have cookie consent implemented, we'll also want to use [Datadog RUM](https://www.datadoghq.com/rum/).
