### ISSUE TITLE
Integrate: Get phone number

### ISSUE THREAD

**Issue by jpmarques66** [reach4help/reach4help#295]
Use the already implemented dummy component related to phone number to integrate with firebase auth.

We will be using firebase phone auth, that will handle the sms for us. Please follow the following link on how to do this. https://firebase.google.com/docs/auth/web/phone-auth

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/295)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#326 - View: Get Phone Number](https://github.com/reach4help/reach4help/issues/326)

**Comment by ashwinkjoseph** [comment]
The integration is already done I believe the mobile adaptation of the view is currently being done. Shall I close this issue @s0 @jpmarques66 ?

**Comment by s0** [comment]
Yes, if it's just view work left let's close this.
