### ISSUE TITLE
Contact organizations to get a clearer view of requirements

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#3]
and whether they'd prefer a white-label or SaaS solution

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/3)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by isma-osy** [comment]
Moved to Icebox to be able to use zenhub as our clean unique project management tool
