### ISSUE TITLE
design view: unsupported location

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#313]
This is the view that appears when a user is logging in from an unsupported location, as we now ask for geolocation at the start.

@telmodias is this still accurate? or will be now be asking for the geolocation only when we ask for their location? I think that may be the case right?

Related: #215

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/313)

*This information is updated automatically. To modify it, please use ZenHub.*

**Blocking:**

* **[BLOCKING: [#320](https://github.com/reach4help/reach4help/issues/320)]** [BLOCKED BY: [#313](https://github.com/reach4help/reach4help/issues/313)] **[UNASSIGNED]** [#313 - Implement view: unsupported location](https://github.com/reach4help/reach4help/issues/316)}

**Comment by telmodias** [comment]
Still trying to clear up my mind on the UX possible for this.
