### ISSUE TITLE
Implement view: unsupported location

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#316]
![image](https://user-images.githubusercontent.com/35262512/81480575-7e13ed80-9222-11ea-87a7-4e2d6d4085b9.png)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/316)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#312 - View: Landing Page](https://github.com/reach4help/reach4help/issues/312)

**Blocked By:**

* ~~[#316 - design view: unsupported location](https://github.com/reach4help/reach4help/issues/313)~~

**Blocking:**

* [BLOCKED BY: [#316](https://github.com/reach4help/reach4help/issues/316)] [[@ashwinkjoseph](https://github.com/ashwinkjoseph)] [#316 - Integrate view: landing page](https://github.com/reach4help/reach4help/issues/320)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/316)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#312 - View: Landing Page](https://github.com/reach4help/reach4help/issues/312)

**Blocked By:**

* ~~[#316 - design view: unsupported location](https://github.com/reach4help/reach4help/issues/313)~~

**Blocking:**

* [BLOCKED BY: [#316](https://github.com/reach4help/reach4help/issues/316)] [[@isma-osy](https://github.com/isma-osy), [@ashwinkjoseph](https://github.com/ashwinkjoseph)] [#316 - Integrate view: landing page](https://github.com/reach4help/reach4help/issues/320)

**Comment by ashwinkjoseph** [comment]
is anyone currently working on this issue? @schowdhury8

**Comment by fulin426** [comment]
I've been assigned and working on it
