### ISSUE TITLE
implement component: layout / header + side drawer

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#324]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/324)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#321 - Component: Layout / Header + Side Drawer](https://github.com/reach4help/reach4help/issues/321)

**Blocking:**

* [BLOCKED BY: [#324](https://github.com/reach4help/reach4help/issues/324)] [#324 - Implement View: PIN: My Requests](https://github.com/reach4help/reach4help/issues/102)
* [BLOCKED BY: [#324](https://github.com/reach4help/reach4help/issues/324)] [#324 - Implement Mobile View: PIN: Request Details](https://github.com/reach4help/reach4help/issues/160)
* [BLOCKED BY: [#324](https://github.com/reach4help/reach4help/issues/324)] [[@puzzledbytheweb](https://github.com/puzzledbytheweb)] [#324 - [New Request] - Add new request screen](https://github.com/reach4help/reach4help/issues/162)
* [BLOCKED BY: [#324](https://github.com/reach4help/reach4help/issues/324)] [#324 - Implement View: PIN: Request created screen (please wait)](https://github.com/reach4help/reach4help/issues/348)

**Comment by ashwinkjoseph** [comment]
is anyone currently working on this issue? @schowdhury8
