### ISSUE TITLE
Complete UX flow for CAV

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#336]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/336)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [[@telmodias](https://github.com/telmodias)] [#337 - Views: CAV Flow](https://github.com/reach4help/reach4help/issues/337)

**Comment by puzzledbytheweb** [comment]
@telmodias I think you've done this, can you confirm?
