### ISSUE TITLE
Design View: sending confirmation code

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#339]
This can probably just be a modification to #338 that replaces the button with some sort of loading indicator...

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/339)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#326 - View: Get Phone Number](https://github.com/reach4help/reach4help/issues/326)

**Blocking:**

* [BLOCKED BY: [#339](https://github.com/reach4help/reach4help/issues/339)] [#339 - Implement view: sending confirmation code](https://github.com/reach4help/reach4help/issues/340)

**Comment by r13serra11** [comment]
Already change it. Can you please review it?
