### ISSUE TITLE
Implement view: sending confirmation code

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#340]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/340)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#326 - View: Get Phone Number](https://github.com/reach4help/reach4help/issues/326)

**Blocked By:**

* ~~[#340 - Design View: sending confirmation code](https://github.com/reach4help/reach4help/issues/339)~~

**Comment by ashwinkjoseph** [comment]
@schowdhury8 is anyone currently working on this issue? please also check #98 as @jpmarques66 had already moved that to done. so this could be done as well.
