### ISSUE TITLE
Find User Testing & QA Lead

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#35]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/35)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by s0** [comment]
Asked @dbenamy if he'd still like to do this.

**Comment by schowdhury8** [comment]
Closing since we have @CorporateInvesther leading QA now
