### ISSUE TITLE
Coordinating Translators

### ISSUE THREAD

**Issue by cinthyaejh** [reach4help/reach4help#379]
Our group started in Helpful Engineering so we can utilize their resources.
There exists a Channel #communication_translations within their slack.
There are a lot of volunteers who offered to translate from just being bilingual wanting to help to professional Translators.

There was an effort to have people list the languages they are comfortable with included below, but there are many more people if you scroll up through the channel.
https://helpfulengineering.slack.com/archives/CVDV5PZLP/p1585005242129100

Feel free to post your needs to the channel or reach out to the individuals directly.
Even if they are not professionals and can just do most of the work translating, we can have multilingual people within our team just give it a quick revision before making it public.

Thank you!

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/379)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
David Yu, head of [VolunteerAtlas](https://www.volunteeratlas.com/) mentioned that the company he works at, [Sportologiq](https://sportlogiq.com/en/) could provide translators in ES and FR if we need it.

**Comment by puzzledbytheweb** [comment]
@cinthyaejh this is something we can do with Crowdin, like we've done with the map right?

**Comment by cinthyaejh** [comment]
There are plugins such as WPLM for Wordpress to automate translations on websites. I think we could do it with Crowdin like the map but isn't that much more work manually adding the translation? Thoughts @s0 ?
