### ISSUE TITLE
Create slack tags for different teams in the big channel and the lead channel

### ISSUE THREAD

**Issue by edmkitty** [reach4help/reach4help#38]
Create slack tags for different teams in the big channel.(Ex: @fe-eng, @be-eng, @ux-eng, @infra, etc). I think the tags are isolated to one channel but if they aren't then the tag will have to look more complex

Create slack tags in the lead channel to divvy up by skillset, or maybe team? Not sure

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/38)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Got done when we got upgraded to Plus!
