### ISSUE TITLE
[Personal-data] - Add user info from firebase to form

### ISSUE THREAD

**Issue by jpmarques66** [reach4help/reach4help#384]
**Is your feature request related to a problem? Please describe.**
Personal data form should be initialized with user information and use the user's profile photo.

**Additional context**
https://www.figma.com/file/OiU7Tl4k1YFfqZQXxLaRrl/Reach4Help?node-id=940%3A465
![image](https://user-images.githubusercontent.com/52417176/79048933-6132cd00-7c18-11ea-824f-fa98ecfe3125.png)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/384)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#325 - Views: Essential Info](https://github.com/reach4help/reach4help/issues/325)

**Comment by davejon1337** [comment]
can i try this one?

**Comment by jpmarques66** [comment]
> can i try this one?

Go for it 🙂

**Comment by jpmarques66** [comment]
> can i try this one?

Are you on our slack already?

**Comment by davejon1337** [comment]
@jpmarques66 No. The slack link in docs expired.

**Comment by jpmarques66** [comment]
> @jpmarques66 No. The slack link in docs expired.

@davejon1337  Just merged a fix, can you check that again please?

**Comment by davejon1337** [comment]
@jpmarques66 can confirm that the link is working.

**Comment by puzzledbytheweb** [comment]
Hey! @axiiomatic did you end up completing this?

**Comment by ashwinkjoseph** [comment]
@puzzledbytheweb this Issue has been completed in PRs #426 and #467
