### ISSUE TITLE
[New Request] - Add "request created" page

### ISSUE THREAD

**Issue by jpmarques66** [reach4help/reach4help#386]
Screen to display after PIN creates a request.

**Describe the solution you'd like**

Tasks:
- [x] Create component
- [x] Integrate with New-request page #162 

**Figma**: https://www.figma.com/file/OiU7Tl4k1YFfqZQXxLaRrl/Reach4Help?node-id=756%3A145

![image](https://user-images.githubusercontent.com/52417176/79050406-b0c9c680-7c21-11ea-9546-3636817ffc14.png)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/386)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#330 - View: PIN: Request something new](https://github.com/reach4help/reach4help/issues/330)

**Comment by puzzledbytheweb** [comment]
@ashwinkjoseph Is this done? If not do you think we can make these issues (good first issue) really visible for new people on Slack?

**Comment by ashwinkjoseph** [comment]
no, This issue hasn't been done yet.
