### ISSUE TITLE
Apply for GitHub Sponsors

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#393]
This requires us to have a bank account or a fiscal sponsor, bank account would be preferable.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/393)

*This information is updated automatically. To modify it, please use ZenHub.*

**Blocked By:**

* **[BLOCKING: [#393](https://github.com/reach4help/reach4help/issues/393)]** [BLOCKED BY: [#21](https://github.com/reach4help/reach4help/issues/21)] [[@s0](https://github.com/s0), [@schowdhury8](https://github.com/schowdhury8), [@puzzledbytheweb](https://github.com/puzzledbytheweb)] [#393 - Get Bank Account](https://github.com/reach4help/reach4help/issues/392)

**Comment by schowdhury8** [comment]
Done! https://github.com/sponsors/reach4help
