### ISSUE TITLE
Apply for SANTA CASA CHALLENGE

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#394]
see: http://mais.scml.pt/casadoimpacto/challenge/

We need to be registered as a Collective Person, which require NPO status.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/394)

*This information is updated automatically. To modify it, please use ZenHub.*

**Blocked By:**

* **[BLOCKING: [#20](https://github.com/reach4help/reach4help/issues/20), [#392](https://github.com/reach4help/reach4help/issues/392), [#394](https://github.com/reach4help/reach4help/issues/394), [#397](https://github.com/reach4help/reach4help/issues/397)]** [[@schowdhury8](https://github.com/schowdhury8), [@puzzledbytheweb](https://github.com/puzzledbytheweb)] [#394 - Register as NGO / NPO](https://github.com/reach4help/reach4help/issues/21)

**Comment by puzzledbytheweb** [comment]
We won't be able to because we missed the deadline to get NPO status
