### ISSUE TITLE
Contact anarchistagency@gmail.com to ask for help contacting all those orgs on the doc

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#4]
(wait for re-branding)

**Comment by puzzledbytheweb** [comment]
I dont seem to be able to login with my official email on Gsuite, looks like a bug. I'm waiting for it to be solved

**Comment by puzzledbytheweb** [comment]
Will not contact due to the role of this org being compiling their doc information, not contacting directly with those organizations
