### ISSUE TITLE
[MAP] Design - view

### ISSUE THREAD

**Issue by r13serra11** [reach4help/reach4help#408]
details in https://github.com/reach4help/reach4help/issues/416

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/408)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [[@isma-osy](https://github.com/isma-osy)] [#413 - Prepare MAP for Go-To-Market / Marketing strategy](https://github.com/reach4help/reach4help/issues/413)

**Comment by isma-osy** [comment]
Moved to Icebox to be able to use zenhub as our clean unique project management tool

**Comment by schowdhury8** [comment]
This was done a while ago too. The landing page is live on https://map.reach4help.org/!
