### ISSUE TITLE
[BRANDING] Creating a style guide for our branding

### ISSUE THREAD

**Issue by r13serra11** [reach4help/reach4help#421]
[ ] moodboard

[ ] logo variations 
          - do
          - don't

[ ]  typography

[ ] colour palette 

 

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/421)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by PatriciaMiranda** [comment]
Já está feito ahahah

A sexta, 17 de abr de 2020, 17:25, Rita Serra <notifications@github.com>
escreveu:
