### ISSUE TITLE
[Personal Data] : update the geolocation reactivation screen

### ISSUE THREAD

**Issue by telmodias** [reach4help/reach4help#422]
**Is your feature request related to a problem? Please describe.**
We need to provide information to teach the user how to re-enable geolocation, in case the user accidentally blocked it.

**Describe the solution you'd like**
Detect the browser name and version and provide accurate instructions on how to re-enable geolocation on the detected browser.

**Describe alternatives you've considered**
Alternatively we could point to a google page opening on another browser window, but this will remove the user focus from our web app and is potentially confusing.

**Additional context**
![Screenshot 2020-04-19 at 04 06 29](https://user-images.githubusercontent.com/30916/79677580-46052600-81f3-11ea-8dbc-933a1a61e08c.png)
![Screenshot 2020-04-19 at 04 06 42](https://user-images.githubusercontent.com/30916/79677583-4998ad00-81f3-11ea-9b07-59ce012cec55.png)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/422)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ashwinkjoseph** [comment]
@telmodias can we close this ?

**Comment by telmodias** [comment]
AFAIK yes @ashwinkjoseph .
