### ISSUE TITLE
UI of CAV Flow View #1: Sidemenu + Navbar

### ISSUE THREAD

**Issue by ZiyangGao1028** [reach4help/reach4help#450]
Since the CAV UX is ready, we are able to start building the UI design of CAV View "Sidemenu + Navbar". Referred by the attached image or this [link](https://www.figma.com/file/OiU7Tl4k1YFfqZQXxLaRrl/Reach4Help?node-id=1055%3A235)

![Screen Shot 2020-04-22 at 8.10.03 PM.png](https://images.zenhubusercontent.com/5e9f44c44d7b4947cc6b5e0a/fe58271e-c4a4-44d8-a170-a50797b26279)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/450)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#449 - CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/449)

**Comment by puzzledbytheweb** [comment]
@ashwinkjoseph I'm confused. Is this related to UI Design or to the actual implementation?
