### ISSUE TITLE
Frontend of CAV Flow View #2: Timeline

### ISSUE THREAD

**Issue by ZiyangGao1028** [reach4help/reach4help#454]
Since the CAV UX is ready, we are able to start building the frontend for CAV View "Timeline". Referred by the attached image or this [link](https://www.figma.com/file/OiU7Tl4k1YFfqZQXxLaRrl/Reach4Help?node-id=1055%3A235).

![Screen Shot 2020-04-22 at 8.26.13 PM.png](https://images.zenhubusercontent.com/5e9f44c44d7b4947cc6b5e0a/96d6b739-0176-484d-8609-89b199a2e59d)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/454)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#452 - CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/452)

**Comment by isma-osy** [comment]
Closed by merged PRs N°:
https://github.com/reach4help/reach4help/pull/556
https://github.com/reach4help/reach4help/pull/555
https://github.com/reach4help/reach4help/pull/553
