### ISSUE TITLE
Firebase for CAV Flow View #2: Timeline

### ISSUE THREAD

**Issue by ZiyangGao1028** [reach4help/reach4help#464]
**UPDATED 22/05/2020**

Need firebase and redux integration for CAV Flow View "[Timeline](https://www.figma.com/file/OiU7Tl4k1YFfqZQXxLaRrl/Reach4Help?node-id=1055%3A235)", essentially to get and set data within the Timeline View after it's built.

- [ ] When a change occurs to a request or an offer, capture the change and add it to the timeline collection in firestore. Impacts the triggers for creation and updation of both offers and requests.

- [ ] HTTP cloud function for retrieving all the requests along with offers associated with it (must also have the filter for request in case we would like to filter by requests, and the offers must also include the lat lng coordinates and the address, in words of the CAV who made the offer

- [ ] Redux actions and functions to use the HTTP function

- [ ] Integrate Redux with the UI and finish integration

![Screen Shot 2020-04-22 at 8.26.13 PM.png](https://images.zenhubusercontent.com/5e9f44c44d7b4947cc6b5e0a/cc634daf-cf84-4ab5-80ad-f1eae601951f)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/464)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#452 - CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/452)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/464)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#452 - CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/452)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/464)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#452 - CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/452)

**Comment by ashwinkjoseph** [comment]
This is done as we moved this logic over to a cloud function
