### ISSUE TITLE
Create package to share breakpoints between the Map project and Web-Client

### ISSUE THREAD

**Issue by puzzledbytheweb** [reach4help/reach4help#485]
**Is your feature request related to a problem? Please describe.**
We are currently using different breakpoints for both the map and the web-client projects, we should consider making a package so that is not duplicated and everything is uniform and nice. 

**Describe the solution you'd like**
Package shared by both projects.

**Describe alternatives you've considered**
@s0 suggested symlinks

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/485)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by s0** [comment]
To clarify these are css media query breakpoints

**Comment by isma-osy** [comment]
Moved to Icebox to be able to use zenhub as our clean unique project management tool
