### ISSUE TITLE
Create action for Accept / Reject Request

### ISSUE THREAD

**Issue by puzzledbytheweb** [reach4help/reach4help#525]
Implement action on Redux, integrating with Firebase

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/525)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Been made a while ago :)
