### ISSUE TITLE
Rework UX design for MVP

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#53]
Now that we've outlined what's going in the MVP here: https://github.com/reach4help/info#mvp

We should re-work the workflows to take this into account, so that we can then move onto design and frontend dev.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/53)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by isma-osy** [comment]
Moved to Icebox to be able to use zenhub as our clean unique project management tool
