### ISSUE TITLE
Design views for MVP

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#54]
Following #53, we need to convert the wireframes into actual designs. The initial app will be a responsive web application, meaning that people can use it in both browsers and desktops, but will be primarily for mobile users, so it's important we get the mobile design down first.

The current UX workflow we're working from is here: https://www.lucidchart.com/invitations/accept/199b5856-1958-4cd7-a708-a9abfbebedb8

For now, these views are ready to be turned into designs:
* [ ] Essential Info / all 4 views
* [ ] Intro

**Comment by s0** [comment]
@telmodias could you list the views that you think are ready to be turned into complete designs above please? :)

**Comment by telmodias** [comment]
For now I would list the following :
- Splash Screen
- Essential Info /  all 4 views
- Intro

**Comment by s0** [comment]
Removed splash screen for now as it's a web app first

**Comment by s0** [comment]
Closing this in favour of ZenHub epic tracking issues
