### ISSUE TITLE
Integrate data from covid-entraide.fr

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#546]
They have an API where they allow consumption of their data: https://covidentraide.gogocarto.fr/api/

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/546)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by shayantist** [comment]
Seems like their website and API are down.
![image](https://user-images.githubusercontent.com/29135917/107989424-7af12d80-6ffc-11eb-9e6f-0e7314d5d51f.png)
Will leave closed until we need to integrate it again.
