### ISSUE TITLE
[BUG] SignUp: Invalid Format error on /phone/entry when entering valid ph#

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#570]
**Describe the bug**
Cannot proceed past /phone/entry screen, as certain phone numbers entered are returning 'Invalid Format' error. Currently, phone numbers need to be prefaced with +1 followed by the area code and phone number. Typically, a user entering a amount number of digits for their phone number should have no trouble validating their ph#. 

Currently, since there is no adaptive validation error message, the user would have no idea what went wrong, and what they need to correct to have their number accepted by the app. This might lead them to believe it just doesn't work. 

**To Reproduce**
1. Go to https://reach4help-staging-web-client.firebaseapp.com/
2. Proceed past the FB auth screen
3. Enter a valid phone number (ex - 514-589-3419 or 5145893419 or 15145893419 or 1 514 589 3419)
4. Notice the invalid format error, cannot move past this screen. 

**Expected behavior**
Valid phone number should be accepted, user is led to the next screen and prompted to enter confirmation code sent by SMS. 

**Screenshots**

![invalid format phone number](https://user-images.githubusercontent.com/65609627/82497774-db2e5f80-9abc-11ea-85a2-eb636c0db690.PNG)

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Version 81.0.4044.138 (Official Build) (64-bit)

**Smartphone**
 - Device: iPhone 7 plus
 - OS: 13.3
 - Browser: Safari
 - Version 13.1

**Additional context**
Many sites add a location dropdown, and phone number field is updated according to the user's location: 

Example: 
![standard invalid format - FB](https://user-images.githubusercontent.com/65609627/82598329-7d5f4d80-9b78-11ea-9dbd-3f1a299f12e3.PNG)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/570)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/570)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ashwinkjoseph** [comment]
I have pushed, a sort - of fix for this. there is a little more proactive version of the error message, which will hopefully reduce the chances of this happening

**Comment by CorporateInvesther** [comment]
Hello, 
If we are comfortable with only accepting phone numbers with this format I can close. But I want to mention that it is not intuitive to ask the user to manually add a + at the beginning of the number when entering phone numbers in an online form.

**Comment by CorporateInvesther** [comment]
Verified Fixed in Build Version 2.0
