### ISSUE TITLE
[BUG] SignUp: Validation error message is gramatically incorrect 

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#571]
**Describe the bug**
The phone number validation error is gramatically incorrect. 

Currently displayed as: 
Your number Invalid format. 
![grammar error - number is Invalid format](https://user-images.githubusercontent.com/65609627/82574876-bdf99f80-9b55-11ea-9813-7b14a29d6bf1.PNG)

Should be changed to any of the following: 

The phone number you provided has the wrong format. 
![standard invalid format error](https://user-images.githubusercontent.com/65609627/82572442-5130d600-9b52-11ea-8581-f323c5d59731.PNG)

or : 
Please enter a valid phone number. 
![standard invalid format - FB](https://user-images.githubusercontent.com/65609627/82572659-ae2c8c00-9b52-11ea-81c9-1e694a028588.PNG)

or: 
Please enter a valid phone number with area code. 
![standard invalid format - Amazon](https://user-images.githubusercontent.com/65609627/82574970-dbc70480-9b55-11ea-8c5b-bf9de35b3604.PNG)

**To Reproduce**
1. Trigger invalid phone number error 
2. Notice error message is gramatically incorrect

**Desktop**
 - OS: Windows 10 
 - Browser Chrome
 - Version 81.0.4044.138 (Official Build) (64-bit)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/571)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by isma-osy** [comment]
POST-MVP

**Comment by mcverter** [comment]
@isma-osy you can close this issue because we have new fone entry screen

**Comment by CorporateInvesther** [comment]
Verified Fixed Build Version 2.0
