### ISSUE TITLE
[BUG] SignUp: Clicking to resend confirmation code leads to blank page, code not resent

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#574]
**Describe the bug**
After user has entered a valid phone number, they are prompted to enter their confirmation code. There is an option to resend the code. Clicking this will lead to a mostly blank page, with the text : 'oops. Not found!' The code is not resent. 

**To Reproduce**
1. Enter a valid phone number
2. When prompted to enter the confirmation code, select 'resend' link
3.  Notice the error page

**Expected behavior**
A code is resent, the user is advised (possibly with text confirming that the code has been resent) 

**Screenshots**
![Image from iOS (1)](https://user-images.githubusercontent.com/65609627/82594772-9b29b400-9b72-11ea-98bd-e725a67a61e3.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Safari
 - Version 13.1

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/574)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by sabind** [comment]
@CorporateInvesther Thank you for filing this. In the future can we confirm if we were using private mode and what the current URL was that lead to the 404 page?

**Comment by ashwinkjoseph** [comment]
I have pushed a fix for this

**Comment by CorporateInvesther** [comment]
> @CorporateInvesther Thank you for filing this. In the future can we confirm if we were using private mode and what the current URL was that lead to the 404 page?

Absolutely, will add this information in the future!

**Comment by CorporateInvesther** [comment]
Verified Fixed on 05-26-2020

Current behavior - clicking 'resend' will return user to /phone/entry page. Phone number needs to be reentered and code will be resent.
