### ISSUE TITLE
[BUG] SignUp: Clicking Privacy & Security Policy and Terms and Conditions links deletes field data

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#576]
**Describe the bug**
At the bottom of the registration page, where the user enters their address & details, clicking the links for both privacy & security policy and Terms and Conditions will delete everything entered in the registration fields.

**To Reproduce**
1. Get to the registration page
2. Fill out address fields either manually, or using the GPS location
2. Click on 'Privacy & Security Policy' or 'Terms and Conditions'
3. Notice that the fields are cleared

**Expected behavior**
Data entered by the user shouldnt be cleared by clicking on either links, forcing them to re-enter all information.

**Screenshots**
Video of the issue here: https://drive.google.com/file/d/1exmr5YEPDA9Seswm90G9ahAyxbRsI2MQ/view?usp=sharing 

**Smartphone:**
 - OS: iOS
 - Browser: Safari
 - Version: 13.1

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/576)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ashwinkjoseph** [comment]
I have pushed a fix for this

**Comment by punita123** [comment]
Current Behaviour is as expected. Regression testing is done. Clicking on 'Privacy and Security Policy' and 'Terms and Conditions' doesn't delete the information entered for registration
