### ISSUE TITLE
[BUG] Main Screen: On 'role info' page, clicking on "Help Others" button leads to a blank page

### ISSUE THREAD

**Issue by punita123** [reach4help/reach4help#579]
**Describe the bug**
On 'role info' page, clicking on "Help Others" button leads to a blank page

**To Reproduce**
Steps to reproduce the behavior

1. Go to https://reach4help-staging-web-client.firebaseapp.com/
2. Go to 'role info' page
3.'How can we assist you' page will be displayed
4. Click on 'Help Others' button
5. The blank screen is displayed

**Expected behavior**
 On 'role info' page, click on  "Help Others" button should display the 'Find Requests page' 

**Screenshots**
![image](https://user-images.githubusercontent.com/65728782/82617933-992a1a00-9b9f-11ea-93d3-afb62e683a5b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
  N/A

**Additional context**
  N/A

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/579)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ashwinkjoseph** [comment]
I have pushed a fix for this issue

**Comment by punita123** [comment]
Regression testing is done! issue resolved.
