### ISSUE TITLE
[BUG] SignUp: User can stop the animation by clicking anywhere in the white square

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#581]
**Describe the bug**
The animation is stopping when the user clicks anywhere in the white square.  It will only restart if the user clicks again.

**To Reproduce**
1. Go to 'Thank you for Signing up" page
2. Click anywhere in the white square
(the image stops)
3. Click again
(the image restart moving)

**Expected behavior**
The image shouldnt stop if the user clicks anywhere on the screen

https://drive.google.com/file/d/1uLfSyyawTn3H1Rc8S7TlIh7DIzneAcWZ/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: W10 Pro
 - Browser Chrome
 - Version 83.0.4103.61

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/581)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by PhilArsHermit** [comment]
This issue is also happening on mobile (iPhone11-Safari)

**Comment by isma-osy** [comment]
POST-MVP
