### ISSUE TITLE
[BUG] Clicking on "Finished" and "Archived" will make the page unresponsive

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#588]
**Describe the bug**
While clicking on any other options in the "Find Requests" section (Open, Accepted, Ongoing), will flow normally, and the user will be able to go to another screen (the map section, Notifications or select another options in the Find Requests section),  if he clicks on either "Finished" or "Archived", the page will get stuck, and will receive a "Page Unresponsive" message and will have to exit the page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/requests/find'
2. Click on the 3 bars button next to map
3. Click on "Find Requests"
4. Select either "Finished" or "Archived"
5. Wait a little, and start clicking like you are trying to change page.
6.  The "Unresponsive Page" message appears

**Expected behaviour**
It should act like the other options where clicking on any buttons would just change the page normally.

**Screenshots**
![Page_Unresponsive_Finished_Requests](https://user-images.githubusercontent.com/65713824/82907821-1c979280-9f35-11ea-8cb3-f3233be16e3e.png)

**Desktop (please complete the following information):**
 - OS: W10 Pro
 - Browser Chrome
 - Version: 83.0.4103.61

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/588)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by isma-osy** [comment]
On hold until deploy: the app isn't complete.

**Comment by punita123** [comment]
Regression Testing is done. The bug is fixed.

**Comment by ashwinkjoseph** [comment]
can you add the appropriate label and close this bug?
