### ISSUE TITLE
[BUG] /Personal-Data - Geolocation is not reactivated when using the R4H modal

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#592]
**Describe the bug**
On /personal-data, when the user selects 'Use GPS' to fill in their address, they can block the initial request to enable location services. However, Reach4Help has a modal that gives the option to Retry Geolocation. Clicking Retry does not make the 'Location Services' prompt reappear, however. Clicking 'Retry Geolocation' returns you to the initial 'Geolocation is not authorized' screen.

URL: https://reach4help-staging-web-client.firebaseapp.com/personal-data

**To Reproduce**
1. Reach the /personal-data screen
2. Click on 'use GPS to get my address'
3. When Location Services Pop up appears, click 'Block' instead of 'Allow'
4. When Geolocation Modal appears, select 'Learn How To Reactivate Geolocation' 

**Expected behavior**
According to the message, the button should trigger the location services prompt. The message reads: 

'You can add your location manually, but it would help us get your position more accurately if you used Geolocation. If you wish to re-activate it, please follow the link'

If we arent capable of reactivating the geolocation with a button, the call to action should be changed. 

**Screenshots**
Geolocation Modal: 
![Geolocation Modal](https://user-images.githubusercontent.com/65609627/82945033-3901f200-9f6a-11ea-9b7d-32c9e1fb688f.PNG)

Geolocation - Try Again
![Retry Geolocation](https://user-images.githubusercontent.com/65609627/82945051-40c19680-9f6a-11ea-81c2-b0e94ed7e9ba.PNG)

**Desktop (please complete the following information):**
Windows - Chrome - Incognito Mode

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/592)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
@sabind @isma-osy @ashwinkjoseph 

I am not sure what the appropriate behavior is.
You can not reenable geolocation if it was expicitly refused on the same browser page.
https://stackoverflow.com/questions/20678707/ask-for-geolocation-permission-again-if-it-was-denied

We could instruct the user to RELOAD the page -- that will allow them to geolocate.  But maybe this screen wants to tell them how to use location services on this phone?  

What is the desired fix?

**Comment by s0** [comment]
"Learn how to reactivate" should show instructions appropriate for the given browser on how to re-enable geolocation. Those were in the figma i think?

**Comment by mcverter** [comment]
![reactivateGeoLocation](https://user-images.githubusercontent.com/1453956/84076647-2513b280-a9a4-11ea-9a3e-82b4825157ff.png)
