### ISSUE TITLE
[BUG]  Ongoing Request Page: Map icon is not working in the bottom navbar

### ISSUE THREAD

**Issue by punita123** [reach4help/reach4help#593]
**Describe the bug**
On 'Ongoing Request" page map icon is not working in the bottom navbar

**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/requests/ongoing'
2. Click on 'map icon"
3. Map icon is disabled 

**Expected behavior**
Clicking on map icon should display find request page

**Screenshots**
![image](https://user-images.githubusercontent.com/65728782/82955017-eb8e8080-9f7b-11ea-99e7-a66243b4c06e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
  N/A

**Additional context**
  N/A

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/593)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by isma-osy** [comment]
Features in this screen aren't available yet. Retest needs to be done once the app is deployed and checking requests are implemented.

**Comment by ashwinkjoseph** [comment]
can you guys test this again now?

**Comment by punita123** [comment]
Regression Testing is done. The bug is fixed.
