### ISSUE TITLE
Test Out COVID-19 HealthAlert Helpline

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#6]
https://paper.dropbox.com/doc/COVID-19-HealthAlert-Helpline-0iwYNF9LYErvZcFJXNkSR

> @schowdhury8 18th March
> It's rather good (they work with the WHO) for information dispersion (updated in realtime) and curbs quite a few myths and misconceptions to tackle misinfo. I have a call with them tomorrow so if anyone has any questions they want me to bring up, lmk!!

**Comment by schowdhury8** [comment]
Tested it out, but there's a lot of better alternatives getting made every day. Since it doesn't seem particularly relevant right now, we'll revisit if we ever need to.
