### ISSUE TITLE
[MENU] Switching user type CAV/PIN

### ISSUE THREAD

**Issue by isma-osy** [reach4help/reach4help#602]
**Is your feature request related to a problem? Please describe.**
Allow users to toggle between being a PIN to a CAV user and being a CAV user to PIN

**Describe the solution you'd like**
On the MENU screen:
![image (2)](https://user-images.githubusercontent.com/1456473/83188933-554b8d80-a128-11ea-908f-7f9d96f7f89e.png)
adding this feature in the same area as sign out

**Describe alternatives you've considered**

**Additional context**

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/602)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by sharmmad** [comment]
Implemented, PR created and merged into development 
https://github.com/reach4help/reach4help/pull/599
