### ISSUE TITLE
[BUG] Capitalisation needed for the "verify" button

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#603]
**Describe the bug**
The "verify" button would look better if it was labeled as "Verify"

**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/" under a new Facebook user
2. Enter a valid phone number
3. Land on "https://reach4help-staging-web-client.firebaseapp.com/phone/verify"
4. Check the "verify" button

**Expected behavior**
A cap "V" would make the button look better

**Screenshots**
![verify_button_Caps_Needed](https://user-images.githubusercontent.com/65713824/83263872-43500600-a18d-11ea-8407-6302b6a9f9e9.png)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Chrome
 - Version: 83.0.4103.61

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/603)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by CorporateInvesther** [comment]
Verified Fixed v2.1.0
