### ISSUE TITLE
[BUG] Words should be removed from certain "Invalid Messages"

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#604]
**Describe the bug**
Theres 2 Invalid message during the Code verification where theres seem to be the same extra words at the beginning.

**1. Invalid Code** 
**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/phone/entry" after entering a phone number
2. Enter a random code and press "verify"

**Expected behaviour**
The invalid message starts with "Your number is The SMS verification code used to create the phone auth credential is invalid.

**2. Take too long to enter the code**
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/phone/entry" after entering a phone number
2. Wait until the code is no longer valid
3. Enter the code
4. Press "verify"

**Expected behaviour**
The invalid message starts with "Your number is The SMS code has expired."

**_In both case, removing the "Your number is" part would make the message understandable._** 

**Screenshots**
![Error_Message_Invalid](https://user-images.githubusercontent.com/65713824/83271472-e9087280-a197-11ea-848d-c0479c089054.png)
![Error_Message](https://user-images.githubusercontent.com/65713824/83271476-eb6acc80-a197-11ea-9c1e-d40ccb31bccc.png)

**Desktop (please complete the following information):**
 - OS: W10 Pro
 - Browser Chrome
 - Version 83.0.4103.61

***Edit
Esther is adding this as well, as it is related to this issue**

Describe the bug
During Phone Entry - /phone/entry and Code Verification /phone/verify, there are both grammar issues and extra words at the beginning.
1. Invalid Code
To Reproduce
Go to 'https://reach4help-staging-web-client.firebaseapp.com/phone/entry" after entering a phone number
Enter a random code and press "verify"
Expected behaviour
Currently the invalid message is "Your number is The SMS verification code used to create the phone auth credential is invalid. Please resend the verification code sms and be sure use the verification code provided by the user., Please Make sure you entered a valid Mobile Number capable of receiving SMS with the country code prefixing it."
Should be changed to:
This verification code is invalid. Please resend the verification code and try again. Make sure to use a valid mobile number with SMS capabilities, prefixed with a country code.
2. Take too long to enter the code
To Reproduce
Steps to reproduce the behaviour:
Go to 'https://reach4help-staging-web-client.firebaseapp.com/phone/entry" after entering a phone number
Wait until the code is no longer valid
Enter the code
Press "verify"
Expected behaviour
Currently, the invalid message is "Your number is The SMS code has expired. Please resend the verification code sms and be sure use the verification code provided by the user., Please Make sure you entered a valid Mobile Number capable of receiving SMS with the country code prefixing it."
Should be changed to:
This verification code has expired. Please resend the verification code and try again. Make sure to use a valid mobile number with SMS capabilities, prefixed with a country code.
3. Phone Number is already in use
To Reproduce:
Go to 'https://reach4help-staging-web-client.firebaseapp.com/phone/entry"
Enter a phone number already associated to an Reach4Help account.
Expected Behavior:
Currently the message is:
Your number is The credential is already associated with a different user account., Please Make sure you entered a valid Mobile Number capable of receiving SMS with the country code prefixing it.
Should be changed to:
This credential is already associated with a different user account. Make sure to use a valid mobile number with SMS capabilities, prefixed with a country code.
In all cases, the "Your number is" is added to the beginning of every message erroneously.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/604)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/604)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by CorporateInvesther** [comment]
This is fixed, however the message still contains some grammatical errors. Please use the messages detailed above, and repasted for clarity here: 

1. Invalid Code
This verification code is invalid. Please resend the verification code and try again. Make sure to use a valid mobile number with SMS capabilities, using the drop down menu to choose your country code.

2. Code Timeout 
This verification code has expired. Please resend the verification code and try again. Make sure to use a valid mobile number with SMS capabilities, using the drop down menu to choose your country code..

3. Phone Number is already in use
This credential is already associated with a different user account. Make sure to use a valid mobile number with SMS capabilities, using the drop down menu to choose your country code.

Will open a new issue with these details.
