### ISSUE TITLE
[BUG] Phone Verify Page: Information, written before 'resend' is blurry

### ISSUE THREAD

**Issue by punita123** [reach4help/reach4help#605]
**Describe the bug**
Phone Verify Page: Information, written before 'resend' is blurry.

**To Reproduce**

1. Go to '.https://reach4help-staging-web-client.web.app/phone/verify'
2. Information, written before 'resend' is blurry

**Expected behavior**
Information, written before 'resend' should be clearly visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/65728782/83297012-c5592280-a1bf-11ea-9614-ed7ffd323bdf.png)

Desktop (please complete the following information):

OS: Windows 10
Browser: Chrome
Version: 81.0.4044.138 (Official Build) (64-bit)

Smartphone (please complete the following information):
N/A

Additional context
N/A

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/605)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by isma-osy** [comment]
related to 613

**Comment by schowdhury8** [comment]
Closing, as #613 addressed this and was closed.
