### ISSUE TITLE
[BUG] /personal-data - Text between options in the checkbox group is inconsistent.

### ISSUE THREAD

**Issue by j-isenberg** [reach4help/reach4help#610]
**Describe the bug**
The text between the options in the checkbox group at the bottom of the /personal-data page is inconsistent. 
Currently: 
1. The wording for the notification and email checkbox is worded as a question, and in second-person. "Would you like us to send you notifications and emails?" The other two options in the group are written in first-person and as a statement. "I am okay with letting Reach4Help use my profile pic" and "I understand and acknowledge the Terms & Conditions." 
_(This option would also benefit from specifying that Reach4Help will send the notifications and emails. The word "us" could imply that the user is also agreeing to receiving emails and notifications from affiliates.)_ 

2. The first option in the group does not have punctuation, whereas the other two do. 

Suggested fixes: 
1. Reword the notification and email text to: "I would like Reach4Help to send me notifications and emails"
2. Add a period. 

https://reach4help-staging-web-client.firebaseapp.com/personal-data

**To Reproduce**
1. Navigate to the /personal-data page. 
2. Scroll below the forms. 
3. Notice the lack of punctuation in the first option. 
4. Notice the difference in wording for the the second option. 

**Expected behavior**
Information and options should be presented in a clear, specific and consistent manner, especially on pages asking the user for personal information, and permission to send emails. 

**Screenshots**
![2020-05-29_inconsistent text](https://user-images.githubusercontent.com/66037391/83307483-d6f7f580-a1d2-11ea-8b70-192a5c76d3de.png)

**Desktop:**
Windows 10 - Chrome - Incognito 

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/610)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Fixed and deployed to https://app.reach4help.org/
