### ISSUE TITLE
[BUG] Phone Entry Page: Information, written above the  'continue' button is blurry.

### ISSUE THREAD

**Issue by punita123** [reach4help/reach4help#613]
**Describe the bug**
Phone Entry Page: Information, written above the 'continue' button is blurry.

**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/phone/entry'
2. Information, written above 'continue' is blurry.

**Expected behavior**
Information, written above the 'continue' button should be clearly visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/65728782/83435347-0ba1c200-a40a-11ea-88f3-1bd2268db74a.png)

Desktop:

OS: Windows 10
Browser: Chrome
Version 83.0.4103.61 (Official Build) (64-bit)

Smartphone (please complete the following information):
N/A

Additional context
N/A

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/613)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/613)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by isma-osy** [comment]
related to 605

**Comment by punita123** [comment]
Regression Testing is done. The bug is fixed.
