### ISSUE TITLE
[BUG] Role Info Page: A Rectangular box with information is missing.

### ISSUE THREAD

**Issue by punita123** [reach4help/reach4help#614]
**Describe the bug**
 Role Info Page: A Rectangular box with information is missing.

**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/personal-data/role-info'
2. A  Rectangular box with information is missing.

**Expected behavior**
A  Rectangular box with information"We believe that everything we do is meaningful. We believe we are capable of enabling people in their sense of togetherness and community. We believe solidarity brings out the best in individuals." should be present.

**Screenshots**
Actual:
![image](https://user-images.githubusercontent.com/65728782/83442699-97b9e680-a416-11ea-8601-027219d3a1e8.png)
Expected:
![image](https://user-images.githubusercontent.com/65728782/83443441-bcfb2480-a417-11ea-8ad3-b5d93acea471.png)

Desktop :

OS: Windows 10
Browser: Chrome
Version 83.0.4103.61 (Official Build) (64-bit)

Smartphone (please complete the following information):
N/A

Additional context
N/A

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/614)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by isma-osy** [comment]
@mcverter : is this fixed?

**Comment by mcverter** [comment]
@isma-osy merged six days ago
