### ISSUE TITLE
[BUG] [WCAG] All pages - Page title needs to be more descriptive.

### ISSUE THREAD

**Issue by j-isenberg** [reach4help/reach4help#617]
**Describe the bug**
Currently, the page titles are all "Reach4Help". Users who interact using a reader will not know what the page they've navigated to until the reader gets through the top part of the page (including the top-nav menu). 
In order to be WCAG compliant, each page needs to have a unique title that describe the topic or purpose. 

**To Reproduce**
1. Navigate to the Reach4Help website. 
2. Navigate through different pages of the website. 
3. Notice all page titles are "Reach4Help"

**Expected behavior**
Each page has a unique title that appears visually in the browser's window/tab. 

**Screenshots**
![2020-06-02_wcag page title](https://user-images.githubusercontent.com/66037391/83541805-2175bc80-a4c8-11ea-96e3-bd90bc4b7d73.png)

**Desktop (please complete the following information):**
 Windows 10 - Chrome - Incognito.

**Additional context**
https://www.w3.org/WAI/WCAG21/quickref/#page-titled

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/617)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
@isma-osy @sabind @ashwinkjoseph 
I think I can do this if i just map the current route to a title string, add the title string to en.json, and add that as a subtitle

**Comment by isma-osy** [comment]
I would qualify this as a change request because its changing the app's behavior
This is post-MVP and needs UX team lookibng into it

**Comment by mcverter** [comment]
@isma-osy I need to clear up a merge error but this is fixed

**Comment by schowdhury8** [comment]
Fixed and deployed on https://app.reach4help.org/
