### ISSUE TITLE
[BUG][WCAG] All pages - Pages require a bypass button

### ISSUE THREAD

**Issue by j-isenberg** [reach4help/reach4help#618]
**Describe the bug**
All pages must include a button that can immediately be tabbed into that will bypass blocks of repeated material (materials that appear on all pages; ie. Home button and top-nav). 
This makes it easier for those only using keyboards to navigate the page, and allows reader-users to skip past repetitive information. 

**To Reproduce**
1. Navigate to any Reach4Help page. 
2. Without clicking into anything, hit tab. 
3. Notice that the logo/homebutton is the first thing to highlight. 

**Expected behavior**
When a user hits tab after the page first loads, a button should appear that allows the user to skip to the main section/information of the page. 

**Screenshots**
Example from Facebook:
![2020-06-02_tab example](https://user-images.githubusercontent.com/66037391/83546735-2427e000-a4cf-11ea-9284-daa723ebf464.png)
Example from Youtube
![2020-06-02_youtube tab example](https://user-images.githubusercontent.com/66037391/83546914-70732000-a4cf-11ea-8e29-b4d869b0f384.png)

**Desktop (please complete the following information):**
windows 10 - Chrome - Incognito. 

**Additional context**
https://www.w3.org/WAI/WCAG21/quickref/#bypass-blocks

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/618)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by isma-osy** [comment]
Winggo
