### ISSUE TITLE
[MVP] Translating the content text into other languages

### ISSUE THREAD

**Issue by isma-osy** [reach4help/reach4help#632]
**Is your feature request related to a problem? Please describe.**
Translating the MVP's content text (text appearing in screens) into the following languages:
Afrikaner (South Africa)
cs-CZCzech
he-IL Hebrew
ja-JP Japanese
pl-PL Polish
ru-RU Russian
tr-TR Turkish
zh-TW Chinese (I)
ar-SA Arabic
da-DK.json  Danish
es-ES.json Spanish
hi-IN.json Hindi
ko-KR.json Korean
pt-BR.json  Portugese (brazil)
sr-SP.json Serbian
uk-UA.json  Ukranian
bn-BD.json  Bengali
de-DE.json  German
fi-FI.json Finnish
hu-HU.json   Hungarian
nl-NL.json  Netherlands
pt-PT.json Portugese
sv-SE.json        Swedish
vi-VN.json Vietnamese
ca-ES Catalan
el-GR Greek
fr-FR French
it-IT Italian
no-NO  Norwegian
ro-RO Romanian
zh-CN Chinese (II)

**Describe the solution you'd like**
Provide a fast and adaptable translation for the MVP release (13/06/2020)
Work in more details later

**Describe alternatives you've considered**

**Additional context**

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/632)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by CorporateInvesther** [comment]
This is great! Want to mention, if launching first in Montreal, french needs to be included.

**Comment by mcverter** [comment]
@isma-osy @CorporateInvesther Per @sabind s remarks in the meeting today:  it appears that most of our translation is already handled by automated translation services.  

I think it might be possible to override these automated translations by editing this file:
https://github.com/reach4help/reach4help/blob/master/web-client/src/translations/translations.json

Is that right, @sabind ?

**Comment by mcverter** [comment]
it should actually be a longer list of languages but whatever.  let's get this done ASAP.  i  was hoping this would be done by the MVP

**Comment by mcverter** [comment]
needs to be translated in non-western languages too like swahili, hausa, haitian creole, etc
