### ISSUE TITLE
[BUG] - PIN - /requests/new - Choosing OTHER type makes undefined field appear

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#635]
**Describe the bug**
As a PIN, on https://reach4help-staging-web-client.firebaseapp.com/requests/new, you can choose between Deliveries / Other. When you choose OTHER in the Type Dropdown, a field appears but it is undefined. It would not be clear to a user what exactly theyre supposed to use that field for. It should have a description above. 

**To Reproduce**
1. Complete sign up, choosing the PIN user type
2. Land on https://reach4help-staging-web-client.firebaseapp.com/requests/new 
3. Scroll down to TYPE dropdown and select OTHER
4. Notice a field appears directly under the Type Dropdown, but no instructions are given to what the user is supposed to use this field for. 

**Expected behavior**
Fields should be clearly defined so that the user enters the correct information, which would in turn make their request for help clear for CAVs. 

**Screenshots**
![Other - Field not identified](https://user-images.githubusercontent.com/65609627/83767967-3da26680-a64c-11ea-8fe9-c7920af7cb2a.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Chrome - Latest version
 - Build Version: 1

**Additional context**

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/635)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by sabind** [comment]
It should read “Please enter your type” but I’m not exactly sure how this field is stored in the backend.

**Comment by sharmmad** [comment]
Other field is being saved in Request.Title

**Comment by CorporateInvesther** [comment]
It does indeed say Enter your Type in Build 2.0. 
It's still unclear in my opinion, because enter your type of what? If this is as designed, I will close. 

![enter your type](https://user-images.githubusercontent.com/65609627/84401379-32fa4b00-abd1-11ea-8fcc-0e576e2d06b4.PNG)

**Comment by schowdhury8** [comment]
For clarity, the text should be "Enter what you need help with"

**Comment by PhilArsHermit** [comment]
Textbox sill showing as "Please enter your type"
![Other_Texbox](https://user-images.githubusercontent.com/65713824/87062190-bb710900-c1da-11ea-9d3a-9656ad9e3717.png)

@schowdhury8 @ashwinkjoseph
