### ISSUE TITLE
[BUG] - /requests/find - User is prompted to help when viewing their own request 

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#637]
**Describe the bug**
On Build1, a user can switch from PIN to CAV. When the same user enters a request for help, then switches to a CAV, clicking on the request for help they submitted will prompt them to help. Clicking on Help (username), the modal will just be dismissed. 

**To Reproduce**
1. Create account
2. as a PIN, create a request for help
3. In the menu, choose "Switch to Volunteer"
4. Go to the map and select the request for help that was created in Step 2
5. Notice the pop up prompts the user to help himself. 

**Expected behavior**
When viewing their own request, user should not be given the option to help himself. There could possibly be a button that would lead them to their Open Requests screen? Or a button that says "View Open Requests"

**Screenshots**
![User can answer his own request](https://user-images.githubusercontent.com/65609627/83775965-975b5e80-a655-11ea-8b67-e4cb5ed01fc4.PNG)

![switch to person in need](https://user-images.githubusercontent.com/65609627/83775984-9f1b0300-a655-11ea-9bcc-2348d36834e0.PNG)

**Desktop (please complete the following information):**
Windows 10
Chrome
R4H version - Build 1

**Additional context**
Will be entering an issue regarding the option to switch between PIN and CAV being present, as it's not supposed to be for the MVP

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/637)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by PhilArsHermit** [comment]
Created a request, then switched to Volunteer, and my Request was not present on the Map, or in the Open Request field.

Closing the ticket
