### ISSUE TITLE
Buttons reach goes all the way to the right of the page

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#638]
**Describe the bug**
All the buttons in the "Settings" menu have a reach that goes all the way to the right of the page.  Meaning that the user can inadvertently click on the button even if the cursor is not on it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/requests/find'
2. Click on the three horizontal bar
3. Get the cursor on any button
- Find Requests
- Open
- Accepted
- Ongoing
- Finished
- Archived
- Contact Us
- Switch to Volunteer
- Sign Out
4. Pass the cursor through the right

**Expected behavior**
The "hand" cursor is still showing, meaning that the user if the user clicks, it will trigger the button even if the cursor is no longer on the button.

**Screenshots**
![Button_Reach](https://user-images.githubusercontent.com/65713824/83777034-ece43b00-a656-11ea-9f6b-b6d9afe79c60.png)

**Desktop (please complete the following information):**
Build 1
 - OS: W10 Pro
 - Browser Chrome
 - Version 83.0.4103.97

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/638)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ashwinkjoseph** [comment]
I agree. This should be fixed by having different styles for when the user highlights or hovers over a button

**Comment by isma-osy** [comment]
Winggo

**Comment by CorporateInvesther** [comment]
Verified Fixed v2.1.0
