### ISSUE TITLE
[BUG] [WEBSITE] - Certain logos on reach4help.org have visual artefacts

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#639]
**Describe the bug**
Certain logos on reach4help.org have visual artefacts. 

**To Reproduce**
1. Go to reach4help.org
2. Scroll down to the logos

**Screenshots**
![small visual artefacts](https://user-images.githubusercontent.com/65609627/83783274-16ed2b80-a65e-11ea-86d0-c43ca83b6f51.PNG)

Issue observed both on Safari - iPhone 7s & Chrome - Windows 10

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/639)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
@schowdhury8 fixed this a month ago, i think
