### ISSUE TITLE
[BUG] [MVP BLOCKER] User can switch from PIN to CAV in the menu

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#641]
PLEASE NOTE - Do not deactivate ability to switch until confirmed we are not including it in MVP. 

**Describe the bug**
Currently, users can switch from CAV to PIN and back again. This is an MVP blocker, and our stance on giving the option to switch back and forth should be reevaluated before release. 

**To Reproduce**
1. go to https://reach4help-staging-web-client.firebaseapp.com/requests/find
2. Open the menu
3. Notice the option to switch from CAV to PIN on the bottom right of the screen. 

**Expected behavior**
Depending on what we 

**Screenshots**
![switch to person in need](https://user-images.githubusercontent.com/65609627/83803475-a274b580-a67a-11ea-94eb-434f73d88864.PNG)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/641)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ashwinkjoseph** [comment]
yes, I agree. this was originally not supposed to go into the app, but then we included for ease of testing while developing.
I think it's best to remove this, and we can discuss this in one of the calls, maybe on monday

**Comment by ashwinkjoseph** [comment]
@sabind what is your opinion on this?

**Comment by schowdhury8** [comment]
We've decided to keep this functionality as people may want to switch back and forth depending on their situation. Plus, we want to encourage giving back if someone was helped :)
