### ISSUE TITLE
[BUG] [WEB-CLIENT] Closing timeline screen routes to new request screen

### ISSUE THREAD

**Issue by schowdhury8** [reach4help/reach4help#659]
**Describe the bug**
If someone wants to check up on a specific request's timeline then go back to their list of requests, they instead get routed to the 'new request' screen. The cancel button doesn't do anything here so the only way to get out of this is to open the sidebar again renavigate to the list of requests. 

![image](https://user-images.githubusercontent.com/29135917/84067183-dccab380-a9e8-11ea-8cb4-053889a1a951.png)
![image](https://user-images.githubusercontent.com/29135917/84053544-e39afb80-a9d3-11ea-87c5-b7fb82b98ec4.png)
![image](https://user-images.githubusercontent.com/29135917/84053638-05947e00-a9d4-11ea-96b3-5da1db832aa0.png)

**To Reproduce**
1. Sign in as PIN.
2. Open a request.
3. Open the sidebar.
4. Click 'Find Requests' then select 'Open'.
5. Click on the request you just created. You're greeted with the timeline view.
6. Click the back button on the top left. 

**Expected behavior**
Clicking the back button on a request should instead go back to the list of requests they were on (in this case 'Open Requests').

![image](https://user-images.githubusercontent.com/29135917/84053544-e39afb80-a9d3-11ea-87c5-b7fb82b98ec4.png)
![image](https://user-images.githubusercontent.com/29135917/84053729-28bf2d80-a9d4-11ea-97a7-493eec832de2.png)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/659)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by PhilArsHermit** [comment]
Verified and closing this ticket.  After creating a request, and accessing the timeline, pressing the Back button is taking me to the "Open Request" page.

I also checked with the "Accept", "Ongoing", and"Finished".
