### ISSUE TITLE
Bigger Close Button (Easier Navigation to Map from side menus and other pages)

### ISSUE THREAD

**Issue by mcverter** [reach4help/reach4help#660]
I don't know how to navigate back to the map when I open up either of the side menus.

The Cancel Button on all pages should stand out more

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/660)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/660)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
![closeButton](https://user-images.githubusercontent.com/1453956/84082600-1fbb6580-a9ae-11ea-8775-c061e6a432bf.png)

**Comment by PhilArsHermit** [comment]
The Red X button is clear to see for the user to see where to click to close the screen
![Red_X_Notifications](https://user-images.githubusercontent.com/65713824/84672878-09099700-aef7-11ea-8b53-7aaa07dd663e.png)
