### ISSUE TITLE
[BUG] CAVs cannot accept requests from PINs

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#667]
**Describe the bug**
Currently, CAVs cannot accept requests from PINs. As a CAV, clicking on HELP on an open request on https://reach4help-staging-web-client.firebaseapp.com/requests/find will dismiss the request modal, but the request hasnt been accepted and there is no way to fulfill it. There is no prompt on the screen letting the user know what the next steps are, or even just to confirm the request is awaiting approval from the PIN. The help request on the map can be clicked again, and the information is unchanged even though the CAV just accepted this request. The user will again be prompted to help. 

The request cannot be found in the CAVs requests menu. 
On the PIN side, the request doesnt appear in the "Accepted Requests" list. 

**To Reproduce**
1. As a PIN, create a request
2. As a CAV, accept this request
3. Notice there is nothing indicating that the request has been accepted. There is no way for the CAV to fulfill the request. 

**Expected behavior**
Requests for help should be able to be fulfilled. 

**Screenshots**
Video of the issue: https://drive.google.com/open?id=1qGug6R0bxC9q4tYsk6dDheH6-7EfSIqz
![PIN screen - accepted requests](https://user-images.githubusercontent.com/65609627/84165718-019f4500-aa42-11ea-94b4-0109afca59a7.PNG)

**Desktop (please complete the following information):**
Used both Chrome and Firefox. 
Build Version - 1

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/667)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by isma-osy** [comment]
TOP PRIORITY

**Comment by isma-osy** [comment]
Please retest following latest deploy in staging

**Comment by CorporateInvesther** [comment]
Verified Fixed on Build Version 2.0
