### ISSUE TITLE
[BUG] Messaging unclear for request flow

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#668]
The messaging is not clear for CAVs and PINs on what to expect when submitting or accepting a request. 

- When a CAV accepts the request, they dont immediately get the contact information. The PIN has to accept the volunteers help first. The CAV should probably be informed of this once they accept the request. Do they get a notification? Do they get an email? How will they know the request for help has been approved and they have access to the contact information?

- Do PINs get a notification once a CAV has offered their help?  Will they receive an email? Where do they go to see if the request has been accepted? Do they need to check back regularly in the app? 

This needs to be communicated clearly to both CAVs and PIN. 

**PIN FLOW**
Step 1 - 
As a PIN on /requests/find, create a NEW REQUEST. Submit the request. 
Step 2
As a PIN, notice that the user is not told where to go to view information about their ongoing request. They are not told that a CAV needs to accept this request, or that as a PIN they will also need to confirm that the PIN has accepted the offer for help before the request can officially begin. 

***expected behavior***
When a PIN submits a request, they should be clearly informed of what the process is like. They need to know to WHEN to check back in the app see if their request for help has been accepted, and WHERE to go to get updates on their request. They need to know HOW to accept this request. In my humble opinion, I think a simple message explaining the process on this screen would be sufficient. (just above the request, after the user has filled out the request information, but BEFORE they submit their request. Maybe a checkbox to confirm they understand the process? Just an idea)

![requests NEW](https://user-images.githubusercontent.com/65609627/84298151-a8581400-ab1c-11ea-8c9e-0751b5800654.PNG)

**CAV FLOW**
Step 1
As a CAV, on a different browser, find the request on the map and accept it by clicking "HELP (PIN's name)". 

Step 2 - 
Since the PIN has not accepted the offer for help from the CAV, the information on how to complete the request for help is not immediately available. The CAV should be aware of WHEN they need to check on information on help request, and understand that its not immediate. HOW it works (PIN needs to accept offer of help, it is possible it will be rejected, etc), WHERE they need to go to check if the offer is accepted or not. If it is accepted, whats next? 

****expected behavior****
The flow is clearly understood by CAV so they know what to expect and when to check back, where to go. In my opinion, the details of the flow could be placed on THIS SCREEN, right before the CAV sends their initial offer to help: 

![CAV help screen](https://user-images.githubusercontent.com/65609627/84298711-8a3ee380-ab1d-11ea-9a8d-9f33893074a9.PNG)
 

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/668)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/668)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
+1, brought this up with @ashwinkjoseph who agreed we need a popup notification after creating a request/accepting a request or doing any major step in the workflow that takes you to the appropriate next screen.

**Comment by isma-osy** [comment]
UX to be upgraded on this one

**Comment by mcverter** [comment]
![newRequestInstructions](https://user-images.githubusercontent.com/1453956/84416873-cf791900-abe2-11ea-8e70-2711719d7b0f.png)

**Comment by schowdhury8** [comment]
# PIN Flow
## First time entering 
> Thank you for joining Reach4Help! As a person in need, you'll be able reach out for help in your area by creating requests. Currently, we can't guarantee that there are volunteers who can help in your area, in which case we'd suggest sharing it with potential volunteers and local volunteer organizations. Thank you for joining us in building this unified platform of help!

## First time creating a request
> Thank you for creating your first request! You can check the status of your request as it progresses each stage from the sidebar: 
> - **Open**: Your request is out there but nobody's offered to help yet.
> - **Accepted**: A volunteer has offered to take up your request, awaiting your confirmation. 
> - **Ongoing**: You accepted a volunteer, who is taking care of your request. 
> - **Finished**: You and the volunteer have agreed that the request has been fulfilled. 
> - **Archived**: You changed your mind and deleted your request. 

> You'll also be receiving notifications as your request passes each stage to remind you of these. If you have any questions or difficulty with this, don't hesitate to contact support@reach4help.org!

## General creating a request
Show a pop-up routing them to the request timeline page with the text:
> Thank you for submitting a request! You'll be notified when a volunteer offers to accept it. To check its status, click/tap here or check "Open Requests" on the sidebar. 

## Accept volunteer help
Send a notification that routes them to the accept volunteer page: 
> A volunteer has offered to help! Click/tap here to accept them or check under 'Accepted Requests' on the sidebar. 

### If accepted: 
> You've accepted `CAV_display_name`'s help on `request_title`! Click/tap here to check its status or check under "Ongoing Requests" on the sidebar. 

### If rejected: 
> You've rejected `CAV_display_name`'s help on `request_title`. You'll be notified again when a volunteer offers to accept it. Click/tap here to check its status or check under "Open Requests" on the sidebar. 

# CAV Flow
## First time entering 
> Thank you for joining Reach4Help! As a volunteer, you'll be able to help people in your area by responding to their help requests. Thank you for joining us in building this unified platform of help!

### There's more stuff to add here, but you can work with this till I finish the others...

**Comment by mcverter** [comment]
https://github.com/mcverter/reach4help/tree/bug/668-unclear-flow

**Comment by mcverter** [comment]
FIRST PAGE PIN SEES WHEN THEY REGISTER

This is also the first time they see NewRequest screen

![PINopeningScreen](https://user-images.githubusercontent.com/1453956/84457091-c5c9d280-ac2f-11ea-94c7-1e796291eed8.png)
