### ISSUE TITLE
[BUG] Find Requests - Two requests with the same postal code are superimposed on the map, only one is accessible

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#669]
**Describe the bug**
When there are two help requests with the same postal code, they will appear one on top of the other. The one on the bottom is not clickable so it cannot be accessed on https://reach4help-staging-web-client.firebaseapp.com/requests/find 

**To Reproduce**
1. Create two or more requests with the same postal code
2. Go to requests/find
3. Notice the pins are one on top of the other

**Expected behavior**
More than one requests at the same postal code, or even several requests from the same person, should be accessible on the map. 

**Screenshots**
![one request and another](https://user-images.githubusercontent.com/65609627/84169636-d703bb00-aa46-11ea-9132-570d0d7738c6.PNG)

Chrome & Firefox, Build Version 1

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/669)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by isma-osy** [comment]
To be fixed POST-MVP

**Comment by mcverter** [comment]
might be worth consulting @s0 about the work he did on this branch
https://github.com/reach4help/reach4help/commits/feat/%23383-add-geolocation-to-userdata

**Comment by mcverter** [comment]
https://github.com/reach4help/reach4help/issues/746
Providing a list view  is a partial solution
