### ISSUE TITLE
[BUG] Long names are truncated on HELP button in Request Modal

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#670]
**Describe the bug**
Long names will be truncated when viewing requests. The request already displays the PIN's name at the top, also displaying it on the button is not in my opinion necessary. If we want to display the name on the button, just using the first name would be sufficient. 

**To Reproduce**
1. Click on an open request on requests/find
2. If PIN has a long name, notice that it is truncated on the "HELP (PIN's name)" button.

**Expected behavior**
Truncated text on a button isn't great. You could either use the display name and have a maximum character limit which is reflected in the HELP button size, only use the first name, or don't display the name at all in the button.

**Screenshots**
![Name truncated](https://user-images.githubusercontent.com/65609627/84172113-9c4f5200-aa49-11ea-8dcd-57b0af77187d.PNG)
![Name truncated2](https://user-images.githubusercontent.com/65609627/84172118-9eb1ac00-aa49-11ea-9626-f23447c46a47.PNG)

**Desktop (please complete the following information):**
 - Chrome & Firefox
- Build Version - 1

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/670)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Super late but...
@all-contributors please add @CorporateInvesther for user testing
