### ISSUE TITLE
[BUG] PIN - New Request cannot be submitted because NEXT button is unavailable

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#677]
**Describe the bug**
On mobile, when a PIN tries to submit a new request (/requests/new), the NEXT button is unavailable. Its placed directly below the screen and is obscured by the menu bar on the bottom. Attempting to scroll down to access it just pops it back into place. 

This was reproduced on a iPhone 7 Plus, on both Safari and Chrome browsers. Issue is not present on desktop. 

**To Reproduce**
1. Go to https://reach4help-staging-web-client.firebaseapp.com/requests/new 
2. Start filling a new request
3. Scroll down to the bottom of the form and try to access NEXT

**Expected behavior**
PIN should be able to access all parts of the new request form on mobile. 

**Screenshots**
Video: https://drive.google.com/file/d/1EtnxMQlgggw5zJS4PrBO80tW6onP1if1/view?usp=sharing

**Desktop (please complete the following information):**
Not present on desktop

***Smartphone***
iPhone 7plus
 - OS: 13.4.1
 - Browser: Chrome & Safari
 - Build Version - 2

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/677)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by btuerker** [comment]
Fixed by https://github.com/reach4help/reach4help/issues/677

**Comment by CorporateInvesther** [comment]
Verified Fixed v2.1.0
