### ISSUE TITLE
[BUG] SignUp - United States is displayed in country dropdown when selecting Canada

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#679]
**Describe the bug**
Choosing Canada in the Country dropdown on the Phone/Entry screen during sign up makes United States appear instead. 

![phone entry canadians](https://user-images.githubusercontent.com/65609627/84318108-e87abf00-ab3b-11ea-81d0-a6e064013b52.PNG)

Canadians have qualified this as a blocker. 
![canada will remember](https://user-images.githubusercontent.com/65609627/84318512-925a4b80-ab3c-11ea-9652-0f2a3034a1a0.PNG)

**To Reproduce**
1. Go to https://reach4help-staging-web-client.firebaseapp.com/phone/entry
2. Choose Canada from the country dropdown
3. Notice the error

**Screenshots**
Video here: https://drive.google.com/open?id=11lyj1tw99XcO3U4qcl1F3M1nrLNFsBIt

**Desktop (please complete the following information):**
Windows - Chrome
Build Version 2.0

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/679)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Poor Canadians, we can't let this slide. Also +1 for the TWD reference :)

**Comment by mcverter** [comment]
@CorporateInvesther lol.  this is fixed on development  @sabind

**Comment by CorporateInvesther** [comment]
This fix should be pushed to https://reach4help-webclient.web.app/phone/entry as well, as outreach is going to be relaying this to canadian contacts who were previously blocked by this screen.

**Comment by CorporateInvesther** [comment]
Verified Fixed, v2.1.0. 

Canadians forgive you this time. :)
