### ISSUE TITLE
+1 vs +11 phone number

### ISSUE THREAD

**Issue by mcverter** [reach4help/reach4help#688]
+16467057784
+116467057784
are both valid numbers.  
too easy to enter the wrong number

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/688)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Fixed and deployed a while ago: 
![image](https://user-images.githubusercontent.com/29135917/85317975-11f2fd80-b4e1-11ea-91f2-86791a113d25.png)
