### ISSUE TITLE
Weird white circle appears on the map when loading the page

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#691]
**Describe the bug**
When accessing the Map page, a stretch circle appears near your location.  it disappear almost instantly. 

**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/'
2. Observe the Map 
3. A white circle appears near your location

**Expected behavior**
In previous build, the circle wasnt appearing.

**Screenshots**
![White_Cercle_Map](https://user-images.githubusercontent.com/65713824/84401781-a9974880-abd1-11ea-9952-f7f6e46a9f2e.png)

**Desktop (please complete the following information):**
 - OS: W10 pro
 - Browser Chrome
 - Version 83.0.4103.97

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/691)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
This is my bug.  I know the cause and will try to fix it.  The circle is causes by the renderng of the geolocation control on the map.  This happens at a certain time during the rendering of the map to cause the weird white circle.  I will investigate the fix ...

**Comment by mcverter** [comment]
@schowdhury8 Sean is working on this one. Please add him to the github @ashwinkjoseph @sabind

**Comment by skspade** [comment]
Hey I'm that Sean, posting here to make it easier to find my github 👍
