### ISSUE TITLE
[BUG] The Volunteer and Person in need are being ask to review themselves

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#692]
**Describe the bug**
After completing a request, both the Volunteer and Person in Need are asked to review themselves.

**To Reproduce**
Steps to reproduce the behaviour:

PhilPhil (Person in Need)
Ruth(Volunteer)
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/' on 2 different browsers (one Volunteer and one Person in Need)
2. Have the Person in Need to create a Request
3. Volunteer ask to get the request.
4. Person in Need accept the request

Behaviour
At that point, the Volunteer sees the Request on the screen, and he is able to Finish the request.
![Volunteer_Screen_1](https://user-images.githubusercontent.com/65713824/84404647-1c55f300-abd5-11ea-8ca7-9d719529edd0.png)

While the Person In Need cant click anywhere
![Person_In_Need-Screen1](https://user-images.githubusercontent.com/65713824/84404800-4dcebe80-abd5-11ea-8d30-8a3d339a5c2e.png)

The Volunteer has to click on "Finish Request" in order to continue the flow
![Volunteer_Screen_2](https://user-images.githubusercontent.com/65713824/84404927-70f96e00-abd5-11ea-994e-f8d6fa3574c8.png)

He then lands on a screen where he is being asked to rate himself
![Volunteer_Screen_3](https://user-images.githubusercontent.com/65713824/84405024-938b8700-abd5-11ea-9bb5-88060e236a37.png)

After he rates himself, the Person in Need sees a Finished screen where he's also being asked to rate himself.
![Person_In_Need-Screen2](https://user-images.githubusercontent.com/65713824/84405206-d5b4c880-abd5-11ea-9df6-f8a788dda336.png)

**Expected behavior**
The Volunteer and Person in Need should rate the other person.  Also it should be the Volunteer who Finish the Request.  

I think this bug is linked to #643, where the Volunteer was unable to see the request in the Open Request section.

**Desktop (please complete the following information):**
 - OS: W10 Pro
 - Browser Chrome
 - Version 83.0.4103.97

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/692)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
@ashwinkjoseph does #781 fix this?

**Comment by btuerker** [comment]
Fixed in here https://github.com/reach4help/reach4help/pull/781, thanks to @ashwinkjoseph 👏

**Comment by PhilArsHermit** [comment]
Tested on R4H v2.1.0

Each users is now correctly reviewing the other one.

Closing the ticket
