### ISSUE TITLE
[BUG] Phone number field preview doesn't reflect the correct format

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#693]
**Describe the bug**
On phone/entry, in the field where the user is supposed to enter their phone number, the following is displayed: 

![enter phone number](https://user-images.githubusercontent.com/65609627/84405415-14e31980-abd6-11ea-8004-8bb2662034e1.PNG)

1234567 doesnt reflect a real phone number with area code. 

**To Reproduce**
1. Go to https://reach4help-staging-web-client.firebaseapp.com/phone/entry
2. Notice the preview in the phone number field.

**Expected behavior**
Should be changed to an example like ex: 5555551111 or 555-555-1111 (if we can process hyphens) 

**Screenshots**
Screenshots included in description. 

**Desktop (please complete the following information):**
Windows - Chrome & Firefox

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/693)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
![phoneInput](https://user-images.githubusercontent.com/1453956/84408952-ce43ee00-abda-11ea-9ed2-7b6d01a3ef72.png)

@CorporateInvesther  the phone input has been cleaned up, at @ashwinkjoseph s suggestion to put the country code back in the phone number row

does this UI change close the issue?
