### ISSUE TITLE
On the "Request Timeline Page' "the back navigation arrow is not working".

### ISSUE THREAD

**Issue by punita123** [reach4help/reach4help#698]
Describe the bug
On the "Request Timeline Page' "the back navigation arrow is not working".

To Reproduce**

1. Go to 'https://reach4help-staging-web-2. client.firebaseapp.com/timeline/ryjNLSLAGB2fqPZHV8uM...'
2. Click on 'back' arrow.
3. The back navigation arrow is not working
3. It brings back to the same page.

Screenshot:
![image](https://user-images.githubusercontent.com/65728782/84416509-4b269600-abe2-11ea-8507-4d78f49367ab.png)

Expected behavior:
The back navigation arrow should be working.

Desktop (please complete the following information):

OS: [Windows]
Browser chrome
Version [ 83.0.4103.97 (Official Build) (64-bit]

Additional context
N/A

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/698)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
@PhilArsHermit added the same issue in #705: 

> **Describe the bug**
> After a request is done, the Person in Need is unable to leave the Request Timeline screen, even after he completed the review.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/' with 2 users
> 2. Create a request, and complete it
> 3. The Volunteer then review the user, and automatically leave the Timeline screen and land in the map section
> 4. Have the Person in Need reviews
> 5. We see the loading screen, but he lands back into the Timeline page.  If he tries to go back (by pressing the arrow), we briefly see the loading symbol, but it just goes back to the Timeline page.
> 
> **Expected behaviour**
> The Person in Need should automatically leave the Timeline page after reviewing the Volunteer, similar to the flow of the Volunteer.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
>  - OS: W10 Pro
>  - Browser Chrome
>  - Version 83.0.4103.97
> 
> 
> 
> 
> 
> --------
> ### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/705)
> 
> *This information is updated automatically. To modify it, please use ZenHub.*
> 
>

**Comment by schowdhury8** [comment]
Fixed and deployed in production, closing. 
![image](https://user-images.githubusercontent.com/29135917/85258145-c44aa680-b488-11ea-8981-5dda328721c1.png)
