### ISSUE TITLE
Exra coding appears in the Ongoing Request title

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#704]
**Describe the bug**
There's extra code in the Ongoing Request title

**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/requests/ongoing'
2. See the title

**Expected behavior**
It should only be "Ongoing Requests"

**Screenshots**
![Ongoing_extracoding](https://user-images.githubusercontent.com/65713824/84504948-d65b6680-ac8a-11ea-887f-c8d0200d1566.png)

**Desktop (please complete the following information):**
 - OS: W10 Pro
 - Browser Chrome
 - Version 83.0.4103.97

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/704)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Fixed, closing.
![image](https://user-images.githubusercontent.com/29135917/85257820-3ff82380-b488-11ea-8fa0-dac54af2771f.png)
