### ISSUE TITLE
Person in Need cant leave the Request timeline screen

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#705]
**Describe the bug**
After a request is done, the Person in Need is unable to leave the Request Timeline screen, even after he completed the review.

**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/' with 2 users
2. Create a request, and complete it
3. The Volunteer then review the user, and automatically leave the Timeline screen and land in the map section
4. Have the Person in Need reviews
5. We see the loading screen, but he lands back into the Timeline page.  If he tries to go back (by pressing the arrow), we briefly see the loading symbol, but it just goes back to the Timeline page.

**Expected behaviour**
The Person in Need should automatically leave the Timeline page after reviewing the Volunteer, similar to the flow of the Volunteer.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: W10 Pro
 - Browser Chrome
 - Version 83.0.4103.97

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/705)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Same as #698 

> Fixed and deployed in production, closing. 
> ![image](https://user-images.githubusercontent.com/29135917/85258145-c44aa680-b488-11ea-8981-5dda328721c1.png)
>
