### ISSUE TITLE
[BUG] Ongoing Request Page: "doesn't display expected information"

### ISSUE THREAD

**Issue by punita123** [reach4help/reach4help#708]
**Describe the bug**
Ongoing Request Page: "doesn't display expected information"

To Reproduce**

1. Go to "https://reach4help-staging-web-client.firebaseapp.com/requests/ongoing"
2. Ongoing Request Page: "doesn't display expected information"

Expected behavior
Ongoing Request Page: "should display expected information"

Screenshots
Current Behavior
![image](https://user-images.githubusercontent.com/65728782/84516914-84bbd780-ac9c-11ea-9a28-ffe88a5dfd8a.png)
Expected:
![image](https://user-images.githubusercontent.com/65728782/84517004-a321d300-ac9c-11ea-988b-948d60f362cb.png)

*Desktop :

OS: [Windows]
Browser chrome
Version [ 83.0.4103.97 (Official Build) (64-bit]

Additional context
N/A

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/708)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by CorporateInvesther** [comment]
closing, duplicate
