### ISSUE TITLE
[BUG] Info modal has extra semicolon

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#712]
**Describe the bug**
The following string has a seemingly misplaced semicolon: 
You can check the status of your request as it progresses each stage from the sidebar:
![infomodal](https://user-images.githubusercontent.com/65609627/84530111-94ddb200-acb0-11ea-8244-fcafb65bf01c.PNG)

in en.json
common -> information_modal -> NewRequestsContainer -> 2

Is it supposed to show a picture of where the sidebar is? If not, removing the semicolon would be a fine fix. 

**To Reproduce**
1. Create new request
2. Notice error in infomodal

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/712)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Seeing as we're refactoring all the text, don't think this applies anymore
