### ISSUE TITLE
Work out estimate for azure credit usage

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#73]
So that we can pass this on to microsoft as an official request.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/73)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by s0** [comment]
cc @sabind @edmkitty @webmonger 

Dan has volunteered to do a cost ballpark based on heroku costs (to give us a ballpark as to what to ask for from Azure)

**Comment by puzzledbytheweb** [comment]
@edmkitty mentioned on Slack that the infra team estimated 600 pounds a month. Might be good to hear her thoughts on this?

**Comment by s0** [comment]
TODO: me: send an estimate of 600GBP to microsoft, and setup an org.

**Comment by s0** [comment]
No longer using Azure, using GCP instead.
