### ISSUE TITLE
Develop unit tests

### ISSUE THREAD

**Issue by mcverter** [reach4help/reach4help#755]
refactoring does not have to wait for test development but good tests will make refactoring faster

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/755)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
e2e is now in #798
