### ISSUE TITLE
[WEB-CLIENT] Add Google authentication 

### ISSUE THREAD

**Issue by schowdhury8** [reach4help/reach4help#761]
**Is your feature request related to a problem? Please describe.**
Add a way for people to login with Google on top of Facebook

**Describe the solution you'd like**
Add Google as a sign-in provider through Firebase and integrate the logic accordingly. 
Then add a "Sign in with Google" button on top of Facebook.
![image](https://user-images.githubusercontent.com/29135917/84807313-dcee3300-b028-11ea-985f-b91d723ac608.png)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/761)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Deployed to staging, tested it and it works. Thank you @Winggo !!

**Comment by Winggo** [comment]
> Deployed to staging, tested it and it works. Thank you @Winggo !!

awesome! no problem
