### ISSUE TITLE
Separate UI and logic and languge for "Offering Support" and "Requesting Help"

### ISSUE THREAD

**Issue by mcverter** [reach4help/reach4help#769]
I am very confused about this screen:

This is The side panel for the CAV View.

First of all "Find Requests" is confusing.  It should be "Map Page" "OfferSupport" "Look for people who need your /support"  Whatever.  It is *not* a list of Requests the same way that "Open Request" and "Accepted Requests" are.  It results in a list of requests.  It is a search page.

Secondly, why is the Volunteer looking at a list of Requests?  
An Volunteer learn about the status of their Offers.

As a PIN, I want to track my Requests for Help
As a CAV, I want to track my Offers of Support

We need to better separate out the logic and language for "Offerng Support" and "Requesting Help".  

These MenuDrawers need different functionality and buttons for Volunteer and PIN
![CAVHomeSide](https://user-images.githubusercontent.com/1453956/84942086-554c0700-b0b0-11ea-9bf9-35751e0e7b0b.png)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/769)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/769)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ashwinkjoseph** [comment]
@schowdhury8 @puzzledbytheweb @isma-osy can you guys take a look at this?

**Comment by schowdhury8** [comment]
I agree, better to rename 'Find Requests' to 'Request Map'.

For the rest of the sidebar, it might be easier/faster to define clearly what each of those _states_ are. 
@r13serra11 made this earlier to show on first sign-in, but it's a good idea to have a '?' icon on the sidebar showing this whenever necessary: 
![image](https://user-images.githubusercontent.com/29135917/85015434-c90e1280-b189-11ea-9cc8-a0fce17389cb.png)
**NOTE**: The states and text for PIN/CAV are gonna be different, but this should clear up much of the confusion for each sidebar item.
