### ISSUE TITLE
Populate map with more organizations (in particular portugal & NYC)

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#77]
We need to add more data to our [Mutual Aid Map](https://map.reach4help.org/).

Instructions for adding new data to the map can be found here: https://github.com/reach4help/reach4help/tree/master/map/src/data

If you have information on projects, but are not able or comfortable editing the data files directly, please feel free to enter the information in this form: https://docs.google.com/forms/d/e/1FAIpQLSd4rbN_UPk3RW3a_9sIbBmdv6pH30jqzWKv8Hem9YDRr-uAfQ/viewform

We would love as much help as possible for this, please comment with an overview of the data you will be adding as you start working on this to prevent duplicated/wasted effort.

For a list of sources, see: https://github.com/reach4help/reach4help/wiki/Map-Project:-Unifying-Mutual-Aid-Group-Directories-and-Maps

Added resources so far:
1. (Version: 14:56 - 2020-03-23, A-Kentucky) https://docs.google.com/document/d/1uP49OQGhosfBN4BOYQvyy_Mu3mpCSOYzip13LksC-S8/edit

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/77)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/77)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/77)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by s0** [comment]
I'm currently going through this, and modifying the schema / types as I go as necessary to fit the data :)

**Comment by s0** [comment]
Done (2) all the way up to end of california now, @sabind will be taking over on data entry for a bit.

**Comment by s0** [comment]
Going to work on this again now, starting from Colorado.

**Comment by s0** [comment]
Stopping at Kentucky with #217 today.

**Comment by kfo42** [comment]
https://mutualaid.nyc/groups/ I saw that you needed mutual aid groups from New York for the map. This page has a CSV file containing 107 different mutual aid groups in NYC.

**Comment by kfo42** [comment]
More mutual aid for students:
https://advocatesforyouth.org/wp-content/uploads/2020/03/Collaborative-Compilation-of-COVID-19-Resources-for-Youth-and-Students.pdf

**Comment by kfo42** [comment]
Additional NYC resources:
https://docs.google.com/document/d/18WYGoVlJuXYc3QFN1RABnARZlwDG3aLQsnNokl1KhZQ/edit

**Comment by kfo42** [comment]
https://actionnetwork.org/groups/search?type=keyword&value=mutual+aid+

**Comment by kfo42** [comment]
4000+ Mutual Aid Groups in the UK
https://docs.google.com/spreadsheets/d/18P898HWbdR5ouW61sAxW_iBl3yiZlgJu0nSmepn6NwM/edit?fbclid=IwAR0oIo1WvDRniBo6RflOnGeNvH_tH5hldrDKVke9IT9OHGnnSoTqS3xoqEU#gid=1451634215

**Comment by kfo42** [comment]
Canadian mutual aid
https://docs.google.com/document/d/1LsHkTBMS0YX_4F7OSAt55ppV0xICi50AXdF62vRw4W8/edit?fbclid=IwAR1vviyNThHuBYKfWe8Y2I1G0AOPJt-f8PzGUGDBZs65mNrqOIqvqU-9_Dg
