### ISSUE TITLE
Round up the average score of rating

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#773]
**Is your feature request related to a problem? Please describe.**
There some score that could have a lot of numbers after the comma.
![Round_Up_Average](https://user-images.githubusercontent.com/65713824/85147187-7cbfe280-b21c-11ea-8a68-43dd2b6002f4.png)

**Describe the solution you'd like**
Have the average score round up to minimum 2 digits after.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/773)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
@PhilArsHermit   One decimal point is better.  
To the coder who fixes this:  
<number>.toFixed(1)
the conversion of string and number is a bit tricky here
