### ISSUE TITLE
Add the Analytics and Crash Reports

### ISSUE THREAD

**Issue by puzzledbytheweb** [reach4help/reach4help#774]
Add the necessary SDK's to our code and activate in the Firebase Console.

**Additional context**
We need this to have this so we track usage for marketing. We also need Crash reports to track performance and errors.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/774)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Done by @cinthyaejh on #777
