### ISSUE TITLE
[WEB-CLIENT] Manual language selector

### ISSUE THREAD

**Issue by schowdhury8** [reach4help/reach4help#786]
**Is your feature request related to a problem? Please describe.**
Currently, we automatically choose a person's language based on a person's browser language. However, as per user feedback, this isn't always the best approach (someone mentioned that their browser is in French but they'd rather use the app in English). 

**Describe the solution you'd like**
As part of the sign up process in #762, create a manual language selector to be shown on the first screen. Also, it'll probably be needed in the settings page as well. 
![image](https://user-images.githubusercontent.com/29135917/85231522-78ace400-b419-11ea-8fa5-4c8fbcf157fd.png)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/786)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
https://github.com/mcverter/reach4help/tree/feature/762-signup-redesign

this is the branch where i have worked on 762.  where is the work for this bug?

**Comment by CorporateInvesther** [comment]
https://github.com/reach4help/reach4help/issues/856

**Comment by CorporateInvesther** [comment]
verified on v2.2.0, closing
