### ISSUE TITLE
[WEB-CLIENT] As a new PIN, I want to provide my phone number when submitting my first request, to get to know the app first

### ISSUE THREAD

**Issue by isma-osy** [reach4help/reach4help#789]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/789)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#804 - [WEB-CLIENT] Sign-up simplification and usability upgrade](https://github.com/reach4help/reach4help/issues/804)

**Comment by mcverter** [comment]
@btuerker @ashwinkjoseph Do not work on this bug until 762 is merged first 
@isma-osy @schowdhury8  @sabind 

https://github.com/reach4help/reach4help/pull/796

**Comment by mcverter** [comment]
src/modules/requests has been refactored.
Do not work on this but until this pull request is merged
https://github.com/reach4help/reach4help/pull/765

@btuerker @ashwinkjoseph @isma-osy @schowdhury8  @sabind
