### ISSUE TITLE
[WEB-Client] As a user, I want to have a settings page, to manage my account and profile information 

### ISSUE THREAD

**Issue by isma-osy** [reach4help/reach4help#791]
**Is your feature request related to a problem? Please describe.**
The app doesn't offer a way for the user to manage his account.

**Describe the solution you'd like**
Initiate the settings functionality:
Create a settings page accessible to a logged-in user
From the settings page, the user can:
-Update his name/login (no unicity checks for now)
-Delete his account and erase his data

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/791)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by sharmmad** [comment]
@isma-osy @r13serra11 Do we have the UX for this page? Also, could you please add some details around the requirements like where to put the link for Settings etc.

**Comment by r13serra11** [comment]
not yet. but will be done soon
