### ISSUE TITLE
[WEB-Client] (TECH-WORK) Implement telemetry on the requests management

### ISSUE THREAD

**Issue by isma-osy** [reach4help/reach4help#792]
**Motivation**
Every time an error occurs in our app via the usage of real users we have no idea it did happen, where it did happen or why did it happen. As such we need to start implementing telemetry so that we have enough data to make educated decisions as to where to focus our efforts. We also need to track the performance of our app as a very long time to load is a detractor to good user experience and customer/user retention. 

**Error Tracking**
Firebase has a service called [Crashlytics](https://firebase.google.com/docs/crashlytics) but apparently it's SDK is not availale for web apps. I'd suggest something like [Sentry](https://sentry.io/welcome/) as it has a generous Free plan, it is not overly expensive once we need more and it is easy to set up. We'll use [Datadog Client-Side JS logging feature](https://docs.datadoghq.com/logs/log_collection/javascript/?tab=npm)

**Performance Monitoring**
In order to get metrics on how our app is responding in the real world, we need something to track load times, and to log events, not only to know which events are being triggered the most but especially to identify which ones are taking the longest to fulfill. To do this we can integrate with the [Firebase Performance SDK](https://firebase.google.com/docs/perf-mon/get-started-web#using-module-bundler).

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/792)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by isma-osy** [comment]
@mdeous : datadog account

**Comment by Winggo** [comment]
Issue can be closed
