### ISSUE TITLE
[WEB-CLIENT] PIN map is gone

### ISSUE THREAD

**Issue by schowdhury8** [reach4help/reach4help#819]
**Describe the bug**
The map for the PIN (seeking help) is gone. @mcverter mentioned this is a CSS issue. 

**To Reproduce**
1. Sign into https://app.staging.reach4help.org/
2. Switch to "Seeking Help" from the sidebar. 
3. Look at what used to be a map (RIP) at the top of the screen. 

**Expected behavior**
![image](https://user-images.githubusercontent.com/29135917/86033623-0ceefa80-ba5b-11ea-9000-ec0431cd63a2.png)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/819)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/819)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
@schowdhury8 talk to @ebrelsford about fixing map css.  @btuerker  might also know

**Comment by sabind** [comment]
@schowdhury8 Please make sure to snap any console logs 😄 . Helps us debug.

**Comment by mcverter** [comment]
![mapErrors](https://user-images.githubusercontent.com/1453956/86131745-05a80b00-bab4-11ea-8fbc-f19c73334248.png)
![cssMap](https://user-images.githubusercontent.com/1453956/86131746-0640a180-bab4-11ea-9655-17787988f36f.png)
![promiseError](https://user-images.githubusercontent.com/1453956/86131747-0640a180-bab4-11ea-99e5-84ce20f3cdde.png)

Not a css error.  Map has nonzero dimensions.   Seems to be an error in the firebase layer.

@schowdhury8 reassigning to @ashwinkjoseph .  maybe @sabind can advise too
