### ISSUE TITLE
[RFC] - Help us grow screen/modal (User Acquisition)

### ISSUE THREAD

**Issue by puzzledbytheweb** [reach4help/reach4help#820]
- Start Date: 29-06-2020
- RFC PR: (leave this empty)
- Issue: (leave this empty)

# Summary
A flow that allows the user to help us grow by sharing the application in Social Media.

# Motivation
We need more influx of users into our app. Since we will be getting our users mostly from existent organizations this proposed solution aims to address the issue we are having growing our network of PIN's. It should also allow us to have a better reach once people see that their friends/connections are using our app.

# Detailed design

![image](https://user-images.githubusercontent.com/35262512/86287650-72b8bf00-bbe0-11ea-97ca-f119362f530d.png)

# Drawbacks

Why should we *not* do this? Please consider:

- implementation cost, both in term of code size and complexity
- being invasive to the user by asking them to share in their Social Networks

# Alternatives

These should be seen not only as alternatives but especially as potential improvements in our User Acquisition funnel:
- A Share button when requests get fulfilled
- Anything else that might be placed in app to get more engagement from potential users

# Adoption strategy

We should advertise this feature to our existent networks. We should incentivise our users by giving them a badge, and therefore start our own efforts to implement a more robust gamification system.

# Unresolved questions
Design is still in progress by @r13serra11 

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/820)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/820)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by r13serra11** [comment]
![Screenshot 2020-07-01 at 18 25 38](https://user-images.githubusercontent.com/62537457/86273519-485b0780-bbc8-11ea-87eb-d84b0d1c37bd.png)

**Comment by puzzledbytheweb** [comment]
@r13serra11 I deleted your comment with the screenshots because I've put them in the description
