### ISSUE TITLE
[WEB-CLIENT] Sign up components clipping through container

### ISSUE THREAD

**Issue by schowdhury8** [reach4help/reach4help#821]
**Describe the bug**
There are components (button and text box) clipping through the sign up screens. 

![image](https://user-images.githubusercontent.com/29135917/86036018-0793af00-ba5f-11ea-88f9-2b57b66e7737.png)

**To Reproduce**
1. Go to https://app.staging.reach4help.org/ on a phone display (or use Chrome dev tools to simulate this)
2. Click on "Continue"

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/821)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by CorporateInvesther** [comment]
Issue verified fixed on v2.1.0
