### ISSUE TITLE
[WEB-CLIENT] Limit available languages in language selector  

### ISSUE THREAD

**Issue by schowdhury8** [reach4help/reach4help#822]
**Describe the bug**
Currently, we only offer support for 4 languages (English, Spanish, French, Portuguese). 
Having every possible language in the selector is a bit misleading and confusing for now, at least until we machine translate those languages.

![image](https://user-images.githubusercontent.com/29135917/86036682-0b740100-ba60-11ea-9fe8-020d61f59a21.png)

**To Reproduce**
1. Go to https://app.staging.reach4help.org/
2. Click on the language selector

**Expected behavior**
For now, just have these languages in the selector: English, Spanish, French, Portuguese.
This will of course expand as the need arises, but we should be clear about what we officially have translated now. 

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/822)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by PhilArsHermit** [comment]
Closing the ticket as the user can now only choose from the 4 different languages.
