### ISSUE TITLE
External account button is overlapping in French

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#823]
**Describe the bug**
The text in the "External account" button is overlapping outside the button .

**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/'
2. Select French
3. Press "Continuez"

![External_Account_Button_French_Overlap](https://user-images.githubusercontent.com/65713824/86039468-785faa80-ba10-11ea-902e-213b2a146eef.png)

**Expected behavior**
The text should stay inside the button.

**Desktop (please complete the following information):**
 - OS: W10 Pro
 - Browser Chrome
 - Version 83.0.4103.116

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/823)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by CorporateInvesther** [comment]
This issue is technically fixed, but it has created a new issue as the new elements that have been added are not translated. 

![Text Not Translated - FR login screen](https://user-images.githubusercontent.com/65609627/86391407-c0c4d580-bc67-11ea-8330-69f5da9e5015.PNG)

Will enter new issue.
