### ISSUE TITLE
Some languages not in the correct order in Language dropdown

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#824]
**Describe the bug**
Theres a couple of language in the dropdown that are not in the correct orders.

**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/login'
2. Scroll through the language list.

Here is the a few examples

![Language_Dropdown_1](https://user-images.githubusercontent.com/65713824/86045363-7b12cd80-ba19-11ea-8ab1-85fefc63f57d.png)

![Language_Dropdown_3](https://user-images.githubusercontent.com/65713824/86045410-8f56ca80-ba19-11ea-99dd-969de6203233.png)

![Language_Dropdown_6](https://user-images.githubusercontent.com/65713824/86045564-c5944a00-ba19-11ea-8bf8-e341b8e52595.png)

![Language_Dropdown_8](https://user-images.githubusercontent.com/65713824/86045625-d93fb080-ba19-11ea-9da9-236bfc4e227b.png)

![Language_Dropdown_9](https://user-images.githubusercontent.com/65713824/86045823-22900000-ba1a-11ea-85be-ea0ab98d4ffb.png)

**Expected behavior**
The language must be in alphabetical order

**Desktop (please complete the following information):**
 - OS: W10 Pro
 - Browser Chrome
 - Version 83.0.4103.116

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/824)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Since we'll be doing #822, this might not be needed

**Comment by mcverter** [comment]
Only four languages are supported so this is a non-issue @schowdhury8 @PhilArsHermit .  issue can be closed
