### ISSUE TITLE
[MAP] Crashes when in portuguese

### ISSUE THREAD

**Issue by puzzledbytheweb** [reach4help/reach4help#829]
**Describe the bug**
When the page loads the site crashes.

**To Reproduce**
1. Go to https://map.reach4help.org with a browser that has the language selected as Portuguese
2. See error

**Expected behavior**
It should show the map

**Screenshots**
![image](https://user-images.githubusercontent.com/35262512/86168613-5fd6b980-bb10-11ea-9638-6edbb59ff22c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
The error appears to occur in the interpolation of this string. `{num}` is probably no defined.
https://github.com/reach4help/reach4help/blob/master/map/src/i18n/langs/pt-PT.json#L166 

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/829)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
HI. I can take this if you show me how to run the map.

The simple fix is to conditionalize this render somehow 
{num && t('templateString.${num}}

The larger issue here is that we shouldn't do so much interpolation in the template strings.  It is confusing to the translator and is error prone and hard to maintain

This is a related issue.  We should not have any extra characters or spaces in the template strings.  Makes everything harder to maintain.

@btuerker We should slow down template interpolation until we investigate further.  maybe it's not as much a problem as i claim  

https://github.com/reach4help/reach4help/issues/811

**Comment by schowdhury8** [comment]
As I mentioned before, the bug isn't in the code, it's in the translations
https://github.com/reach4help/reach4help/blob/master/map/src/i18n/langs/pt-PT.json#L166
It should probably be resolved via Crowdin instead of [editing the translation files directly](https://www.youtube.com/watch?v=otCpCn0l4Wo).

**Comment by schowdhury8** [comment]
Should be fixed with #922
