### ISSUE TITLE
Country code in Phone Number

### ISSUE THREAD

**Issue by mcverter** [reach4help/reach4help#831]
Go to PhoneEntry Page
Enter Digits
Enter Country
Country Code still in Phone Number 

Number displays as '+1us8670987' or '+1ca8670987'

Cause:  number dropdown uses country code as value to differentiate between '1ca' = Canada '1us'=UnitedStates

Country code isn't being stripped out early enough.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/831)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by Tapudp** [comment]
https://github.com/reach4help/reach4help/pull/854

PR for the same.

**Comment by mcverter** [comment]
There are a lot of things now broken in the phone entry component.  Much functionality has been lost, and many bug fixes too.  Will be refixing these now.  I am assigning myself to this bug
