### ISSUE TITLE
Verify App Matches Figma

### ISSUE THREAD

**Issue by mcverter** [reach4help/reach4help#832]
Make sure App matches [@r13serra11's Figma designs](https://www.figma.com/file/OiU7Tl4k1YFfqZQXxLaRrl/Reach4Help?node-id=220%3A120).  Fix css as needed

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/832)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/832)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
@isma-osy This is a really good issue I'd suggest making into an epic to cover each section of the app. Quite a few people (especially new devs!) can work out css in different parts of the app parallelly.
