### ISSUE TITLE
[BUG] LOGIN - FR - Elements on /login screen are partially translated

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#835]
**Describe the bug**
On the login screen, following fix of #823, new elements are not translated. 

![Text Not Translated - FR login screen](https://user-images.githubusercontent.com/65609627/86391856-73953380-bc68-11ea-8086-623448bb74ee.PNG)

"or" and "Sign up with email" should be 
"ou" and "Inscrivez-vous avec votre courriel/adresse électronique" 

**To Reproduce**
1. Go to https://reach4help-staging-web-client.firebaseapp.com/
2. Click on French
3. Select 'Continuez'
4. Notice some elements are still in english

**Expected behavior**
Pages should be completely in french

Windows 10 - Chrome Browser 
R4H v2.1.0

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/835)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ashwinkjoseph** [comment]
I am fixing this bug now
