### ISSUE TITLE
[Bug] Text in 'Cannot Help" is overlapping

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#837]
**Describe the bug**
The "Cannot Help" text in the button is cut off 

**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/' as a Volunteer
2. Click on 'View List of Requests with a Request

![Cannot_Help_Button](https://user-images.githubusercontent.com/65713824/86395160-cc1aff80-bc6d-11ea-8ce2-e305eb8cd64d.png)

**Expected behavior**
The user should see the entire text within the button

**Desktop (please complete the following information):**
 - OS: W10 Pro
 - Browser Firefox
 - Version 78.0.1
R4H v2.1.0

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/837)

*This information is updated automatically. To modify it, please use ZenHub.*

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/837)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
@schowdhury8 why is this high priority?

**Comment by schowdhury8** [comment]
Fixed in #929
