### ISSUE TITLE
[Bug] Too much spacing between Type and the dropdown

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#839]
**Describe the bug**
When creating a request, the Type dropdown is too far from the label

**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/' as a PIN
![Type_Dropdown_spaces](https://user-images.githubusercontent.com/65713824/86397229-70527580-bc71-11ea-93d8-14e1d50f28b9.png)

**Expected behavior**
The dropdown should be closer to the label name

**Desktop (please complete the following information):**
 - OS: W10 Pro
 - Browser Chrome
 - Version 83.0.4103.116

R4H v2.1.0

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/839)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by maksimgm** [comment]
I'd like to take this issue, if it is still relavent

**Comment by puzzledbytheweb** [comment]
> I'd like to take this issue, if it is still relevant

Hey! @ashwinkjoseph can you confirm that this issue is still worth doing?
