### ISSUE TITLE
[Bug] Wrong Finish Request message

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#841]
**Describe the bug**
When the Request is finish, the Volunteer is shown a message to ask him if he's sure that he wants to finish Deliveries from (Volunteer).  The PIN should see this message, and be the first to finish the request.

**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/' as  PIN
2. Open another browser and go to 'https://reach4help-staging-web-client.firebaseapp.com/' as  Volunteer
3. Have the PIN create a request
4. Volunteer request to help
5. PIN accept it
The Volunteer then have the option to to Finish the Request.  If he pressed the Finish Request button, he is then asked if he's sure that he wants to finish Deliveries from (himself)
![Finish_Request_To_Himself](https://user-images.githubusercontent.com/65713824/86482560-34c2b480-bd20-11ea-9620-68bf3cd88416.png)

**Expected behavior**
It should either be:

1) Change the name so that the Volunteer seethe PIN name instead of him
2) Have the PIN to finish the Request first

**Desktop (please complete the following information):**
 - OS: W10 Pro
 - Browser  Firefox
 - Version 78.0.1

R4H v2.1.0

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/841)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ashwinkjoseph** [comment]
I am working on this bug now
