### ISSUE TITLE
[Bug]Wrong name shown in "Thank you for rating..."

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#842]
**Describe the bug**
After reviewing the other person, a quick pop up appears, and its thanking us for rating ourself. 

**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/' as a PIN and create a request
2. Log in as a Volunteer in another browser and accept the request
3. As the Pin accept the request
4. In the Volunteer screen, Finish the Request, and rate the PIN
![Rating](https://user-images.githubusercontent.com/65713824/86485281-5f177080-bd26-11ea-9f4a-0a9fa78de8da.png)

**Expected behavior**
It should said "You rated (PIN) with:

**Desktop (please complete the following information):**
 - OS: W10 Pro
 - Browser Chrome
 - Version 78.0.1

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/842)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by leadersheir** [comment]
I'd like to take this on. But I'm confused which component I should be looking into.
