### ISSUE TITLE
Update CONTRIBUTING.md to include forking/PRing clearly

### ISSUE THREAD

**Issue by schowdhury8** [reach4help/reach4help#855]
**Describe the feature**
We should make our guidelines for contributing to the project (forking, making a pull request, etc.) a bit more clearly. 
https://github.com/reach4help/reach4help/blob/master/CONTRIBUTING.md#your-first-contribution

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/855)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
@schowdhury8 
This is a bit confusing because we have two CONTRIBUTING.md files. 
I don't think we need the one at the top level because we have one at web-client/ subdirectory
Can we get rid of the top level file or reduce it significantly to just a link to web-cient/Contributing.md
