### ISSUE TITLE
[BUG] Support email in FR tutorial prompts is incorrect (support@crowdin.com)

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#857]
**Describe the bug**
In all french tutorial popups, the email listed to contact us is listed as support@crowdin.com. 

**To Reproduce**
1. Trigger tutorial popups in french
2. Scroll to the bottom and notice the support email listed.

**Expected behavior**
Should be our reach4help support email address.

**Screenshots**
<img width="395" alt="support crowdin" src="https://user-images.githubusercontent.com/65609627/86625640-67c0ae80-bf93-11ea-805a-375a5b2aefed.PNG">

Observed on Win10 Chrome (latest)
Build v2.2.0

**Additional context**
I suspect this maybe the case for all translated languages but have yet to confirm. 

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/857)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
It looks like Shayan already fixed this.  @ashwinkjoseph I am adding some new language strings to French, Spansh, and Portugese.  Please merge i18n-master for next r.c.

![ifyouneed](https://user-images.githubusercontent.com/1453956/86825443-5a6ff680-c05d-11ea-94be-78ce6860df52.png)
