### ISSUE TITLE
[BUG] Cannot dismiss the phone entry modal 

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#859]
**Describe the bug**
Currently, the user only needs to enter their phone number once they submit their first new request, or respond to their first request. However, once the phone number entry modal appears, there is no way to dismiss it. 

**To Reproduce**
1. As a PIN, submit your first request. As a CAV, accept your first request
2. Once the phone entry modal appears, try to dismiss it (clicking off the modal, pressing escape on desktop)

**Expected behavior**
You should be able to dismiss a modal, either by 'X'-ing out, cancel button, close button, or clicking outside of the modals boundaries. For accessibility, there needs to be a keyboard accessible way to close the modal (typically, ESC). 

Whatever is chosen, the option to dismiss the modal should be there.

**Screenshots**
<img width="480" alt="phone modal" src="https://user-images.githubusercontent.com/65609627/86635281-e2dc9180-bfa0-11ea-9427-507c47628468.PNG">

Observed on Win10 - Chrome (latest)
Build v2.2.0

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/859)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
@schowdhury8 @CorporateInvesther 

I am not clear whether this is a feature or a bug.
The phone number is a requirement for making a request.  The user should not be able to proceed with the PIN flow if no phone number is specified.  

I will try to make this change now but the modal will reappear if the user hits "Continue" again.

**Comment by schowdhury8** [comment]
@mcverter At least my rationale for this is that in my 'UX research', people turned around here and wanted to check out the app a bit before they put in their phone number. But you are absolutely right, it should definitely reappear until they have verified a phone number.

**Comment by mcverter** [comment]
@schowdhury8 ok. i talked it over with joseph.  the discussion brought up a lot of other issues which hopefully we can adress in the meeting

**Comment by CorporateInvesther** [comment]
The issue was not for the presence of this modal, but the fact that once its open, it cant be dismissed. Its not standard practice, and the user should be able to start responding, and either change their mind or realize that they cant help finally, or they want to check it out on the map one more time. 

Lots of articles on this, here is a snippets: 

**Closing a modal**
Actions inside modals should be clearly marked. There should be a clear path forward (“continue”) and back (“cancel”), in addition to a clearly labeled way to close the modal without taking any action at all. When a modal window is closed, return focus to the last active element on the page behind the modal.

Modal windows are always closable by clicking or tapping:

A delete minicon or label in the upper right corner
The next action button or link
Anywhere outside the modal window
ESC key on a keyboard

https://cfpb.github.io/design-manual/page-components/modals.html#:~:text=Closing%20a%20modal&text=There%20should%20be%20a%20clear,the%20page%20behind%20the%20modal.

**Comment by mcverter** [comment]
Not a good first issue.  Several vectors of redesign required.
