### ISSUE TITLE
Decide on UI library to use

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#86]
* [x] David to come up with list to show Cinthya

**Comment by comoser** [comment]
## List to discuss with @r13serra11 and @cinthyaejh :

- [AntD](https://ant.design/)
- [SemanticUI](https://semantic-ui.com/)
- [MaterialUI](https://material-ui.com/)
- [Shards](https://designrevision.com/downloads/shards-react/)

**Comment by comoser** [comment]
Going with [antd](https://ant.design/)
