### ISSUE TITLE
[Bug] Top of the Map option is cut off for Volunteer

### ISSUE THREAD

**Issue by PhilArsHermit** [reach4help/reach4help#872]
**Describe the bug**
The options in the top of the map when you are a Volunteer is cut off

**To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/requests/find" as a Volunteer
2. Check the map

Firefox
![Map_Option_Cut_Off_Firefox](https://user-images.githubusercontent.com/65713824/87162343-ccca1c00-c293-11ea-8b84-2b879c72919b.png)

Chrome
![Map_Option_Cut_Off_Chrome](https://user-images.githubusercontent.com/65713824/87162508-0733b900-c294-11ea-9126-e08b72beff2f.png)

Expected
Chrome as a PIN
![Map_Chrome_PIN](https://user-images.githubusercontent.com/65713824/87163393-47476b80-c295-11ea-8b60-2f43c6d2c523.png)

**Desktop (please complete the following information):**
 - OS: W10 Pro
 - Browser Chrome & Firefox
 - Version 83.0.4103.116 & 78.0.2

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/872)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by schowdhury8** [comment]
Fixed by @mcverter in #867
