### ISSUE TITLE
Add component library to web-client

### ISSUE THREAD

**Issue by jpmarques66** [reach4help/reach4help#90]
We should think of a component library to help with component layout. 

My suggestion, much inspired in @luisFilipePT, is [rebass](https://rebassjs.org/), especially since we have styled-components.

**Comment by rbgoncalves** [comment]
@jpmarques66 David said in today's meeting that we should wait to have some mockups before picking a UI lib or, as an alternative, pick one to impose the design styles. So, before picking this issue we should definitely choose our desired approach.

**Comment by jpmarques66** [comment]
> @jpmarques66 David said in today's meeting that we should wait to have some mockups before picking a UI lib or, as an alternative, pick one to impose the design styles. So, before picking this issue we should definitely choose our desired approach.

Yep, you're right. Maybe we can use something like material-Ui. Anyway, let's wait for further advancements.

**Comment by jpmarques66** [comment]
Closing this in favor of #94. Please check that issue for further details.
