### ISSUE TITLE
4.3 As an unauthenticated user, I must be taken through the sign in/sign up flow when I try to create a request

### ISSUE THREAD

**Issue by Apfx1945** [reach4help/reach4help#906]
As an unauthenticated user, I must be taken through the sign-in/sign up flow when I try to create a request.

Acceptance Criteria:

- The map has to have a button to create a request. 

- Once clicked that button, the user is to be taken through the authentication flow which can either appear as a pop-up or as redirections. 

Technical Details:
1. Add a new parameter called `partialProtection` whose type would be boolean and would be an optional attribute in the interface for [module definition interface](https://github.com/reach4help/reach4help/blob/3fa6292da64a4c90fac692a6173cb257ab7565cf/web-client/src/types/module.d.ts#L8) - the purpose of this attribute is to indicate that we want to know if the user is authenticated or not and also the stage at which the user is in the authentication flow.
2. Add a new route called `PartialProtectedRoute.tsx` in the [main routes directory](https://github.com/reach4help/reach4help/tree/development/web-client/src/pages/routes). This route should be similar to the [Protected Route](https://github.com/reach4help/reach4help/blob/development/web-client/src/pages/routes/ProtectedRoute.tsx) but instead of redirections, it should first check if the user is fully onboarded onto the platform or not and save it to `localStorage` or as a `cookie` with key as `onboarded` and value as a boolean indicating whether the user finished onboarding themselves or not.
2.a Dispatch actions for observing the user using the `observeUserAction` defined in the [authActions](https://github.com/reach4help/reach4help/blob/development/web-client/src/ducks/auth/actions.ts). you can refer to [Protected Route](https://github.com/reach4help/reach4help/blob/development/web-client/src/pages/routes/ProtectedRoute.tsx) to see an example
2.b use `useSelector` from the `react-redux` library to observe `state.auth.user`
2.c mount an effect using `useEffect` which will monitor the user `state.auth.user` and to see if the user is logged in or not. if the user is logged in, dispatch the action for obtaining the profile and privileged information of the user using the `observeProfile` and `observePrivileged` defined in [profileActions](https://github.com/reach4help/reach4help/blob/development/web-client/src/ducks/profile/actions.ts)
2.c use `useSelector` from the `react-redux` library to observe `state.profile`
2.d return the loader component defined at [LoadingWrapper](https://github.com/reach4help/reach4help/blob/development/web-client/src/components/LoadingComponent/LoadingComponent.tsx) until both `state.auth.observerReceivedFirstUpdate` and `state.profile.observerReceivedFirstUpdate` becomes true just as in [Protected Route](https://github.com/reach4help/reach4help/blob/development/web-client/src/pages/routes/ProtectedRoute.tsx)
2.e Mount another effect using `useEffect` which would trigger on changes to `state.user` and to `state.profile`. This effect should:
2.e.a Check if the user is signed in (state.auth.user is existing)
2.e.b Check if the user has a phone number associated with themselves (state.auth.user.phoneNumber exists or not)
2.e.c Check if the user has an address associated with them or not (state.profile.privilegedInformation.address exists or not)
2.e.d If all the above checks are present, then set the key `onboarded` in `localStorage` as true else set it as false
2.f if both `state.auth.observerReceivedFirstUpdate` and `state.profile.observerReceivedFirstUpdate` are true, return the component as a route, just as in [profileActions](https://github.com/reach4help/reach4help/blob/development/web-client/src/ducks/profile/actions.ts)
3 Inside the [New Request controller](https://github.com/reach4help/reach4help/blob/development/web-client/src/modules/requests/containers/NewRequestsContainer/NewRequestsContainer.tsx), retrieve the key stored in localStorage as `onboarded`, if it is false or not present, mount the [modal for authentication](https://github.com/reach4help/reach4help/blob/development/web-client/src/pages/modals/phoneNumber.tsx)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/906)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#904 - Map Page](https://github.com/reach4help/reach4help/issues/904)

**Comment by schowdhury8** [comment]
@Sangat21 expressed interest in working on this!

**Comment by schowdhury8** [comment]
@edwardmercado expressed interest in working on this!
