### ISSUE TITLE
4.4 As an authenticated user, I want to see requests on a map, so that I can decide which of them I want to help

### ISSUE THREAD

**Issue by Apfx1945** [reach4help/reach4help#908]
As an authenticated user, I want to see requests on a map, so that I can decide which of them I want to help.

Acceptance Criteria: 

- Verify that the map is centered on the user's GPS position. 

- Verify that a pop-up shows up when the user clicks a request.

- Verify that the information of the selected request shown on the pop up is: name & location of the person who made the request; description & type of request (delivery or other). 

- The user must be presented with the option to reject/ignore or make an offer for each of these requests.

Refer to [4.1](https://github.com/reach4help/reach4help/issues/905) for technical details, both of these are to be done together

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/908)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* ~~**[EPIC]** [#904 - Map Page](https://github.com/reach4help/reach4help/issues/904)~~

**Comment by schowdhury8** [comment]
@Sangat21 expressed interest in working on this!

**Comment by ashwinkjoseph** [comment]
This is related to 4.1 and doesn't need additional attention
