### ISSUE TITLE
4.6 As an authenticated user, I want to create a request

### ISSUE THREAD

**Issue by Apfx1945** [reach4help/reach4help#909]
As an authenticated user, I want to create a request.

Acceptance Criteria: 

- The map has to have a button to create a request.

- Once clicked that button, the user is redirected to the flow and the pages for creating a new request. 

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/909)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* ~~**[EPIC]** [#904 - Map Page](https://github.com/reach4help/reach4help/issues/904)~~

**Comment by schowdhury8** [comment]
@Sangat21 expressed interest in working on this!
