### ISSUE TITLE
1.4 As an authenticated user, I want to be able to delete my account

### ISSUE THREAD

**Issue by Apfx1945** [reach4help/reach4help#914]
As an authenticated user, I want to be able to delete my account.

Acceptance Criteria:

- All the ongoing and pending requests have to be canceled. 

- All the ongoing and pending offers have to be canceled.

- The request attached to the canceled offer has to transition to a canceled state if the offer was accepted for the request. The request will not be affected if the offer wasn’t accepted. 
The user’s personal information has to be replaced with the words “Deleted User” for Display Name,  “deleteduser” for username,  “deleted address” for streetAddress, LatLng object pointing to (0.0) for latLng in all the requests and offers which stored the users' information as snapshots.

- All the user's information is erased from the database by being replaced with the words “Deleted User” for Display Name, or  “deleteduser” for username, or  “deleted address” for all text fields in address objects, LatLng object pointing to (0.0) for latLng. 

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/914)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#910 - Authentication and Profile](https://github.com/reach4help/reach4help/issues/910)

**Comment by schowdhury8** [comment]
@edwardmercado expressed interest in working on this!

**Comment by divyeshairmeet** [comment]
![image](https://user-images.githubusercontent.com/58542990/93378275-d797c300-f879-11ea-9b7a-526b5622dfdd.png)

Made these CSS changes, I'm facing some issues while committing.

**Comment by Tapudp** [comment]
![image](https://user-images.githubusercontent.com/8810813/93378529-378e6980-f87a-11ea-973e-bb64f86c1ef2.png)

Updated these CSS changes, I am facing some husky related errors while committing.

```
husky > commit-msg (node v10.16.3)
⧗   input: css changes for delete button and top-panel
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky > commit-msg hook failed (add --no-verify to bypass)
error Command failed with exit code 1.
```
