### ISSUE TITLE
4.1.4 Refactor Requests Page

### ISSUE THREAD

**Issue by puzzledbytheweb** [reach4help/reach4help#927]
Parent Issue: #905 

Currently, our [Find Requests page](https://github.com/reach4help/reach4help/blob/development/web-client/src/modules/requests/containers/FindRequestsContainer/FindRequestsContainer.tsx) uses our own implementation of the map component and we fetch the data from firebase using a cloud function. instead, we need to fetch it from algolia. In the process, we should also change the map from our own implementation to [algolia's widget](https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/geo-search/react/#hits-on-the-map):

1.  Once [Find Requests page](https://github.com/reach4help/reach4help/blob/development/web-client/src/modules/requests/containers/FindRequestsContainer/FindRequestsContainer.tsx) initiates, dispatch action created in step 3 and obtain the search keys.
 
2. Until this is obtained, render the [loading wrapper](https://github.com/reach4help/reach4help/blob/development/web-client/src/components/LoadingComponent/LoadingComponent.tsx). 

3. Once the response is obtained in the redux state, [initiate the algolia search client and instant search client using the search key and the index obtained](https://www.algolia.com/doc/guides/building-search-ui/installation/react/#with-a-build-system).

4. If the user is authenticated (check if `state.auth.user.uid` exists or not), use the [configure component](https://www.algolia.com/doc/api-reference/widgets/configure/react/#props) to [filter queries](https://www.algolia.com/doc/api-reference/api-parameters/filters/?language=javascript) to the once that the user hasn't participated in yet. This can be done by negating the filter for checking if the user exists either in the `participants` array or in the `rejected` array of each document in the index which can be done by adding the filter `NOT (participants:${state.auth.user.uid} OR rejected:${state.auth.user.uid})`

5. Copy the [GeneralRequests Model](https://github.com/reach4help/reach4help/blob/development/functions/src/models/GeneralRequests/index.ts) and [UnAuthenticatedRequests Model](https://github.com/reach4help/reach4help/blob/development/functions/src/models/UnauthenticatedRequests/index.ts) into [web-client's models directory](https://github.com/reach4help/reach4help/tree/development/web-client/src/models) and make the appropriate changes to the types being used to fix any errors that typescript an eslint would throw.

6. Add the additional fields added to the [Requests Model in the functions project](https://github.com/reach4help/reach4help/blob/development/functions/src/models/requests/index.ts)into the [Requests Modal existing in the web-client](https://github.com/reach4help/reach4help/blob/development/web-client/src/models/requests/index.ts)

7. Do the same for the RequestsWithOffersAndTimeline Model and copy additional fields from [RequestsWithOffersAndTimeline Model in the functions project](https://github.com/reach4help/reach4help/blob/development/functions/src/models/requests/RequestWithOffersAndTimeline.ts) to the [RequestsWithOffersAndTimeline Model in the web-client project](https://github.com/reach4help/reach4help/blob/development/web-client/src/models/requests/RequestWithOffersAndTimeline.ts)

8. create a new component level state variable named `currentRequest` whose type would be a union of `GeneralRequests Model` and `UnAuthenticatedRequests Model` with the default value as undefined.

9. create a new component level state variable named `showRequest` whose type would be a boolean and default value would be false.

10. When rendering each of the results obtained from algolia, it should attach an `onClick` handler which would set the value of `showRequest` as true and that of `currentRequest` as hit from algolia but converted into an instance of `GeneralRequests Model` if the user is authenticated and `UnAuthenticatedRequests Model` if the user is not authenticated.

11. Create a new component that would take an instance of `UnAuthenticatedRequests Model` as a prop and handlers for rejection and for accepting as props and would render the request as per the design : ![image.png](https://images.zenhubusercontent.com/5e8f583e55bd2e46e02d2e3d/bdcceae9-dda9-4257-8ae1-d813536acb51)

12. modify the existing [requestItem component](https://github.com/reach4help/reach4help/blob/development/web-client/src/modules/requests/components/RequestItem/RequestItem.tsx#L281) to accept an instance of `GeneralRequests Model` instead of the `Requests Model` as it's prop type for the request

13. In the render function of the controller, if `showRequest` is true and a value is present for `currentRequest`, render the new component created in 4.k if the user is unatuthenticated and render the existing [requestItem component](https://github.com/reach4help/reach4help/blob/development/web-client/src/modules/requests/components/RequestItem/RequestItem.tsx) component if the user is authenticated. Note: This component has to be rendered on top of the map and the results from algolia being rendered as markers

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/927)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [[@gilwong00](https://github.com/gilwong00), [@vignesh-manel](https://github.com/vignesh-manel), [@puzzledbytheweb](https://github.com/puzzledbytheweb)] [#905 - 4.1 As an unauthenticated user, I want to see requests on a map, so that I can check them out. ](https://github.com/reach4help/reach4help/issues/905)

**Comment by ashwinkjoseph** [comment]
This is currently being worked on by Dan Fox

**Comment by alexjball** [comment]
[Here are the screens in Figma](https://www.figma.com/file/OiU7Tl4k1YFfqZQXxLaRrl/Reach4Help?node-id=4127%3A2938)
