### ISSUE TITLE
6.1.4 When the user opens the MyRequests tab, it should use the instantsearch SDK to fetch all the posts from GeneralRequests Index using the SDK while using the filters option in algolia search to retrieve only the posts the user has created with the type as ask

### ISSUE THREAD

**Issue by gorostiaga** [reach4help/reach4help#958]
When the user opens the MyRequests tab, it should use the instantsearch SDK to fetch all the posts from GeneralRequests Index using the SDK while using the filters option in algolia search to retrieve only the posts the user has created with the type as ask

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/958)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** **[BLOCKING: [#974](https://github.com/reach4help/reach4help/issues/974), [#982](https://github.com/reach4help/reach4help/issues/982)]** **[UNASSIGNED]** [#950 - 6.1 As a PIN, I want to see and filter all the requests that I have created, so that I can choose among them.](https://github.com/reach4help/reach4help/issues/950)

**Comment by alexjball** [comment]
I give this a shot this week.
