### ISSUE TITLE
Implement view: get phone number

### ISSUE THREAD

**Issue by comoser** [reach4help/reach4help#98]
Request the phone number from the user to start the SMS validation process

- [x] Build dummy visual page component
- [ ] Adapt to mobile design

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/98)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#326 - View: Get Phone Number](https://github.com/reach4help/reach4help/issues/326)

**Blocked By:**

* ~~[#98 - Design View: Get phone number](https://github.com/reach4help/reach4help/issues/338)~~

**Comment by ashwinkjoseph** [comment]
@jpmarques66 @schowdhury8 is this issue done? can we close this issue?
